lxh/lxh/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from . import settings

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}, name='media'),
    path('admin/', admin.site.urls),
    path('pylxh/', include('society.urls')),
]

lxh/society/urls.py
#coding:utf-8
from django.urls import path, re_path
from . import views


app_name = 'society'
urlpatterns = [
    # 后台管理界面
    path('admin/login/', views.ad_login, name='ad_login'),
    path('admin/login_check/', views.ad_login_check, name='ad_login_check'),
    path('admin/index/', views.ad_index, name='ad_index'),
    # # 资讯管理
    # 栏目
    path('admin/category/', views.ad_category, name='ad_category'),
    path('admin/category/add/', views.ad_category_add, name='ad_category_add'),
    path('admin/category/add/2', views.ad_category_add2, name='ad_category_add2'),
    path('admin/category/change/', views.ad_category_change, name='ad_category_change'),
    path('admin/category/change2/', views.ad_category_change2, name='ad_category_change2'),
    path('admin/category/delete/', views.ad_category_delete, name='ad_category_delete'),
    path('admin/category/all_cate/', views.ad_all_cate, name='all_cate'),
    # 文章审核
    path('admin/art/', views.ad_article, name='ad_article'),
    path('admin/art/add', views.ad_article_add, name='article_add'),
    path('admin/art/change', views.ad_article_change, name='article_change'),
    path('admin/art/delete', views.ad_article_delete, name='article_delete'),
    path('admin/art/all_art/', views.ad_all_art, name='all_article'),
    # 审核是否通过
    path('admin/art/check/', views.art_check, name='art_check'),
    # # 系统管理
    # 公告
    path('admin/sys/notice', views.sys_notice, name='sys_notice'),
    # 友情链接
    path('admin/sys/blogrool', views.sys_blogrool, name='sys_blogrool'),
    path('admin/sys/blogrool/add', views.sys_blogrool_add, name='sys_blogrool_add'),
    # 数据备份
    path('admin/sys/data', views.sys_data, name='sys_data'),

    # 欢迎页
    path('admin/welcome/', views.welcome, name='welcome'),
    # 退出
    path('admin/logout/', views.ad_logout, name='ad_logout'),


    # 前端界面
    path('main/', views.main, name='main'),
    path('login/', views.login, name='login'),
    # 短信验证
    path('note/', views.note_code, name='note_code'),
    # 注册
    path('regis/', views.regis, name='regis'),
    path('regis_check/stu/', views.regis_check_stu, name='regis_check_stu'),
    path('regis_check/pri/', views.regis_check_pri, name='regis_check_pri'),
    # 忘记密码
    path('forget/pas/', views.forget_pas, name='forget_pas'),
    # 个人中心页面
    # 个人资料
    path('a/', views.geren, name='a'),
    path('change/data/', views.change_data, name='change_data'),
    path('iss/content/', views.iss_cont, name='iss_cont'),
    path('iss/<int:a>/', views.my_iss, name='my_iss'),
    path('i', views.my_vip, name='my_vip'),
    path('j', views.my_score, name='my_score'),
    path('k', views.pay, name='pay'),
    path('l', views.gift_ex, name='gift_ex'),
    path('g', views.new_message, name='new_message'),
    path('change/pwd/', views.change_pwd, name='change_pwd'),
    path('change/pwd2', views.change_pwd2, name='change_pwd2'),
    path('logout/', views.login_out, name='logout'),
    # 文章详情
    # path('article/deta/', views.article_deta, name='article_deta'),
    path('main/<int:a>', views.main_type, name='main_type'),
    path('fl', views.flash, name='flash'),
    path('fldeta<int:id>', views.flash_detail, name='flash_detail'),
    path('arti/<int:id>', views.article_deta, name='article_deta'),
    path('vote', views.di_vote, name='di_vote'),
    path('share/<int:id>', views.share_arti, name='share_arti'),
    path('share_suce', views.share_success, name='share_success'),
    path('com', views.comm, name='comm'),
]

lxh/tinymce/urls.py
# Copyright (c) 2008 Joost Cassee
# Licensed under the terms of the MIT License (see LICENSE.txt)
from django.conf.urls import url

from tinymce import views

urlpatterns = [
    url(r'^spellchecker/$', views.spell_check, name='tinymce-spellcheck'),
    url(r'^flatpages_link_list/$', views.flatpages_link_list, name='tinymce-linklist'),
    url(r'^compressor/$', views.compressor, name='tinymce-compressor'),
    url(r'^filebrowser/$', views.filebrowser, name='tinymce-filebrowser'),
]

lxh/society/forms.py
#coding:utf-8
from django import forms
from society.models import *
from django.utils.translation import ugettext_lazy as _


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['type', 'content']
        widgets = {
            'type': forms.TextInput(attrs={'class': 'input-text', 'id': 'type'}),
            'content': forms.Textarea(attrs={'class': 'textarea', 'onkeyup': '(this).Huitextarealength(this,200)', 'id': 'content'})
        }


# class StuForm(forms.Form):
#     class Meta:
#         model = Student
#         fields = ['username', 'password', 'phone']
#         widgets = {
#             'username': forms.TextInput(attrs={'class': 'form-control', 'id': 'contact_name', 'placeholder': '你的用户名...'}),
#             'password': forms.PasswordInput(attrs={'class': 'form-control', 'id': 'contact_pass', 'placeholder': '你的密码...'}),
#             'phone': forms.TextInput(attrs={'class': 'form-control', 'id': 'contact_phone', 'placeholder': '你的手机号...'})
#         }

# 社团负责人资料修改
class PriForm(forms.ModelForm):
    class Meta:
        model = Principal
        fields = ('photo', 'info', 'phone')
        labels = {'photo': _('头像'), 'info': _('简介'), 'phone': _('手机号')}
        widgets = {
            'info': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '写点什么？'}),
            'phone': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '输入手机号'})
        }


#密码修改
# class PripassForm(forms.Form):

lxh/society/views.py
import random
import urllib
import time

from django.shortcuts import render,HttpResponse, redirect
from django.urls import reverse
from django.http import HttpResponseRedirect, JsonResponse
from django.contrib import messages
from django.contrib.auth import authenticate, login as _login, logout
from django.contrib.messages import get_messages
from django.core.files.base import ContentFile
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q
import os
from lxh import settings
from .models import *
from .tools import *
from django.contrib.auth.decorators import login_required
from .forms import *
from django.views.decorators.csrf import csrf_exempt
# Create your views here.


# 后台界面
# 登录
def ad_login(request):
    return render(request, 'society/backstage/admin_login.html')


# 登录验证
def ad_login_check(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            _login(request, user)
            messages.info(request, '登录成功')
            return HttpResponseRedirect(reverse('society:ad_index'))
        else:
            messages.info(request, '用户名或密码错误')
            return render(request, 'society/backstage/admin_login.html')
    else:
        return redirect('society:ad_login')


# 欢迎页
@login_required(login_url='society:ad_login')
def welcome(request):
    return render(request, 'society/backstage/welcome.html')


# 后台详情页
@login_required(login_url='society:ad_login')
def ad_index(request):
    return render(request, 'society/backstage/admin_index.html')


# 栏目界面
@login_required(login_url='society:ad_login')
def ad_category(request):
    search = request.POST.get('search')
    if search is not None:
        if not search.isdigit():
            cate_list = Category.objects.filter(type__contains=search)
        else:
            cate_list = Category.objects.filter(Q(id=search) | Q(type__contains=search))
    else:
        cate_list = Category.objects.all()
    return render(request, 'society/backstage/category-list.html', {'cate_list': cate_list})


# 栏目添加
@login_required(login_url='society:ad_login')
def ad_category_add(request):
    storage = get_messages(request)
    return render(request, 'society/backstage/category-add.html', locals())


@login_required(login_url='society:ad_login')
def ad_category_add2(request):
    type = request.POST.get('type')
    content = request.POST.get('c_content')
    if not type:
        messages.info(request, '类目名称不能为空')
        return HttpResponseRedirect(reverse('society:ad_category_add'))
    if not content:
        messages.info(request, '描述内容不能为空')
        return HttpResponseRedirect(reverse('society:ad_category_add'))
    if Category.objects.filter(type=type).exists():
        messages.info(request, '该类目已存在')
        return HttpResponseRedirect(reverse('society:ad_category_add'))
    Category.objects.create(type=type, content=content)
    messages.info(request, '添加成功')
    return HttpResponseRedirect(reverse('society:ad_category'))


# 修改
@login_required(login_url='society:ad_login')
def ad_category_change(request):
    c_id = request.GET.get('c_id')
    if c_id is None:
        return HttpResponseRedirect(reverse('society:ad_category'))
    if not c_id.isdigit():
        return HttpResponseRedirect(reverse('society:ad_category'))
    try:
        category = Category.objects.get(pk=c_id)
    except Category.DoesNotExist:
        return HttpResponseRedirect(reverse('society:ad_category'))
    form = CategoryForm(instance=category)
    return render(request, 'society/backstage/category-change.html', locals())


@login_required(login_url='society:ad_login')
def ad_category_change2(request):
    c_id = request.POST.get('c_id')
    try:
        category = Category.objects.get(pk=c_id)
    except :
        messages.info(request, '访问不存在')
        return HttpResponseRedirect(reverse('society:ad_category'))
    form = CategoryForm(request.POST, instance=category)
    if form.is_valid():
        form.save()
        messages.info(request, '修改成功')
    else:
        messages.info(request, '修改失败')
    return HttpResponseRedirect(reverse('society:ad_category'))


# 删除
@login_required(login_url='society:ad_login')
def ad_category_delete(request):
    c_id = request.GET.get('c_id')
    if c_id is None:
        return JsonResponse({'status': 0, 'msg': '删除失败'})
    try:
        category = Category.objects.get(id=c_id)
    except Category.DoesNotExist:
        return JsonResponse({'status': 0, 'msg': '删除失败'})
    if category.article_set.all():
        return JsonResponse({'status': 2, 'msg': '该类目下有文章，不能删除'})
    category.delete()
    return JsonResponse({'status': 1, 'msg': '删除成功'})


# 栏目批量删除
def ad_all_cate(request):
    return render(request, 'society/backstage/category-add.html')


# 文章审核
@login_required(login_url='society:ad_login')
def ad_article(request):
    search = request.POST.get('search')
    if search is not None:
        if not search.isdigit():
            art_list = Article.objects.filter(title__contains=search)
        else:
            art_list = Article.objects.filter(Q(id=search) | Q(title__contains=search))
    else:
        art_list = Article.objects.all().order_by('-distribute_date')
    return render(request, 'society/backstage/article-list.html', {'articles': art_list})


def art_check(request):
    art_id = request.GET.get('art_id')
    if Article.objects.filter(id=art_id).exists():
        article = Article.objects.get(id=art_id)
        sta = request.GET.get('status')
        if sta == '1':
            article.status = 1
        elif sta == '2':
            article.status = 2
        article.save()
        return JsonResponse({'status': 1, 'msg': '修改成功'})
    else:
        return JsonResponse({'status': 2, 'msg': '修改失败'})



@login_required(login_url='society:ad_login')
def ad_article_add(request):
    return render(request, 'society/backstage/article-add.html')


@login_required(login_url='society:ad_login')
def ad_article_change(request):
    return render(request, 'society/backstage/article-change.html')


def ad_article_delete(request):
    return render(request, 'society/backstage/article-delete.html')


# 批量删除文章
def ad_all_art(request):
    id_str = request.GET.get('id_str')
    if not id_str:
        return JsonResponse({'status': 0, 'msg': '删除失败'})
    article_id_str = id_str.split(',')
    art = Article.objects.filter(id__in=article_id_str)
    for article in art:
        file_path = str(article.image)
        full_path = settings.MEDIA_ROOT + file_path
        if file_path != '20181024/07.jpg':
            os.remove(full_path)
        article.delete()
    return JsonResponse({'status': 1, 'msg': '删除成功'})


# # 系统管理
# 系统公告
def sys_notice(request):
    return render(request, 'society/backstage/system-notice.html')


# 友情链接
def sys_blogrool(request):
    return render(request, 'society/backstage/system-blogrool.html')


def sys_blogrool_add(request):
    return render(request, 'society/backstage/system-blogrool-add.html')


# 数据字典
def sys_data(request):
    return render(request, 'society/backstage/system-data.html')


# 退出登录
def ad_logout(request):
    action = request.GET.get('action')
    if action == 'logout':
        logout(request)
        messages.info(request, '退出成功')
    return HttpResponseRedirect(reverse('society:ad_login'))











# 前端


# 登录
def login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        role = request.POST.get('role')
        pasnew = add_pass(password)
        # print('------------------------------')
        # print(pasnew)
        if role == '学生':
            if Student.objects.filter(username=username).exists():
                student = Student.objects.get(username=username)
                if student.password == pasnew:

                    request.session['username'] = username
                    request.session['photo'] = str(student.photo)
                    request.session['phone'] = student.phone
                    request.session['info'] = student.info
                    check = request.POST.get('check', None)
                    if check is not None:
                        request.session['password'] = password
                    return redirect('society:change_data')
                else:
                    err2 = '密码错误'
                    return render(request, 'society/baseone/login.html', locals())
            else:
                err1 = '用户不存在'
                return render(request, 'society/baseone/login.html', locals())
        elif role == '社团负责人':
            if Principal.objects.filter(Q(stu_num=username) | Q(phone=username)).exists():
                if len(username) == 11:
                    principal = Principal.objects.get(phone=username)
                else:
                    principal = Principal.objects.get(stu_num=username)
                if principal.password == pasnew:
                    request.session['username'] = principal.username
                    request.session['photo'] = str(principal.photo)
                    request.session['phone'] = principal.phone
                    request.session['mass'] = principal.mass
                    request.session['info'] = principal.info
                    request.session['vip'] = principal.vip
                    request.session['leave_count'] = principal.leave_count
                    request.session['score'] = principal.score
                    request.session['user_code'] = principal.user_code
                    request.session['stu_num'] = principal.stu_num
                    try:
                        if request.POST['check']:
                            request.session['password'] = password
                    except:
                        del request.session['password']

lxh/society/templates/society/base2.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Title</title>
        {% load static %}
        <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-theme.css' %}">
        <link rel="stylesheet" href="{% static 'css/reset.css' %}">
        <link rel="stylesheet" href="{% static 'society/css/ba1_title.css' %}">
        <link rel="stylesheet" href="{% static 'society/css/basetwo/base2.css' %}">
        {% block css %}{% endblock %}
    </head>
    <body>
        <div class="ba1_head">
            <div class="head1_left clear">
                <a href="{% url 'society:main' %}"><img src="{% static 'image/logo.png' %}" alt=""></a>
            </div>
            <div class="head1_right">
 <!--<button class="fbcontent clear" ><a href="" class="iss">退出登录</a></button>-->
                {% if request.session.user_code == '1' %}
                    <button class="fbcontent clear" ><a href="{% url 'society:iss_cont' %}" class="iss">发布内容</a></button>
                {% else %} {% endif %}
                <a href="{% url 'society:change_data' %}"><img src="{% url 'media' request.session.photo %}" alt="" width="44px" height="42px" class="base-head-img"></a>

            </div>
        </div>

        <div class="ba_left">
            <div class="head_por">
                <div class="head_por_top">
                    <img src="{% url 'media' request.session.photo %}" alt="" width="72px" height="72px" class="base-head-img">
                        <div class="top_myname">
                        <span class="myname">{{ request.session.username }}</span></div>
                </div>
                <div class="head_por_bot">
                    <div class="bot_left">
                        <div class="bot_left_top">
                            剩余积分
                        </div>
                        <span class="bot_left_bot">
                            {{ request.session.score }}
                        </span>
                    </div>
                    <div class="bot_cent">
                    </div>
                    <div class="bot_right">
                        <div class="bot_right_top">
                            剩余发布次数
                        </div>
                        <span class="bot_right_bot">
                            {{ request.session.leave_count }}
                        </span>
                    </div>
                </div>
            </div>
            <div class="list-bar">
                <ul class="nav nav-pills nav-stacked">
                  <li role="presentation" class="vip1">
                      <a href="{% url 'society:my_vip' %}">
                          <img src="{% static 'society/image/my_vip.png' %}" alt="">
                          <span class="fun_name">我的会员</span>
                      </a>
                  </li>
                    <li role="presentation" class="vip1">
                      <a href="{% url 'society:my_score' %}">
                          <img src="{% static 'society/image/my_jf.png' %}" alt="">
                          <span class="fun_name">我的积分</span>
                      </a>
                  </li>
                  <!--<li role="presentation"><a href="{% url 'society:iss_cont' %}"><img src="{% static 'society/image/post_n.png' %}" alt=""> <span class="fun_name">发布内容</span></a></li>-->
                  <li role="presentation" ><a href="{% url 'society:my_iss' 3%}"><img src="{% static 'society/image/post_n.png' %}" alt=""> <span class="fun_name">我的发布</span></a></li>
                  <li role="presentation"><a href="{% url 'society:new_message' %}"><img src="{% static 'society/image/xxx_n.png' %}" alt=""> <span class="fun_name">消息通知</span></a></li>
                  <li role="presentation" class="dropdown clear">
                      <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                          <img src="{% static 'society/image/sz.png' %}" alt=""> <span class="fun_name">设&nbsp;&nbsp;&nbsp;置</span> <img src="{% static 'society/image/xia.png' %}" class="xia">
                      </a>
                       <ul class="dropdown-menu">
                          <li role="presentation"><a href="{% url 'society:change_data' %}">个人资料</a></li>
                           <li role="presentation"><a href="{% url 'society:change_pwd' %}">修改密码</a></li>
                           <li role="presentation"><a href="{% url 'society:logout' %}">退出登录</a></li>
                       </ul>
                  </li>
                </ul>
            </div>
        </div>

        <div class="ba_right">
            <div class="ba_right_title">
                <div class="title1_left_point">
                </div>
                <span class="ba_title">
                    {% block title%}
                        欢迎
                    {% endblock %}
                </span>
            </div>
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>
<script src="{% static 'js/jquery-3.3.1.js' %}"></script>
<script src="{% static 'bootstrap/js/bootstrap.js' %}"></script>
<script type="text/javascript" color="112,128,144" opacity='3' zIndex="-10" count="123" src="http://cdn.bootcss.com/canvas-nest.js/1.0.1/canvas-nest.min.js"></script>
{% block js %}
{#    <script src="{% static 'news/js/login.js' %}"></script>#}
    <script>
        {% if messages %}
            {% for message in messages %}
                alert({{ message }});
            {% endfor %}
        {% endif %}
    </script>
{% endblock %}

lxh/society/templates/society/main.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>最后一步不不不</title>
        {% load static %}
        <link rel="stylesheet" href="{% static 'css/swiper-4.3.5.min.css' %}">
        <link rel="stylesheet" href="{% static 'society/css/reset.css' %}">
        <link rel="stylesheet" href="{% static 'society/css/ba1_title.css' %}">
        <link rel="stylesheet" href="{% static 'society/css/main.css' %}">
    </head>
    <body>
        {% load poll_extras %}
        <div class="ba1_head">
            <div class="head1_left clear">
                <a href="{% url 'society:main' %}"><img src="{% static 'image/logo.png' %}" alt=""></a>
            </div>
            <div class="head1_right">
                {% if request.session.user_code == '1' %}
                <button class="fbcontent clear" ><a href="{% url 'society:iss_cont' %}" class="iss">发布内容</a></button>
                {% elif request.session.user_code == '0' %}
                <button class="fbcontent clear" ><a href="{% url 'society:logout' %}" class="iss">退出登录</a></button>
                {% else %}
                <button class="fbcontent clear" ><a href="{% url 'society:login' %}" class="iss">马上登录</a></button>
                {% endif %}
                {% if 'photo' in request.session %}
                <a href="{% url 'society:change_data' %}"><img src="{% url 'media' request.session.photo %}" alt="" width="35px" height="35px" class="base-head-img"></a>
                {% else %}
                    <a href="{% url 'society:login' %}"><img src="{% url 'media' '20181024/07.jpg' %}" alt="" width="35px" height="35px" class="base-head-img"></a>
                {% endif %}
            </div>
        </div>
        <div class="ba_left">
            <div class="ba_left_top clearf">
                <div class="swiper-container">
                    <div class="swiper-wrapper">
                        <div class="swiper-slide"><img src="{% static 'society/image/u211.jpg' %}" alt=""></div>
                        <div class="swiper-slide"><img src="{% static 'society/image/u210.jpg' %}" alt=""></div>
                        <div class="swiper-slide"><img src="{% static 'society/image/lbyt.png' %}" alt=""></div>
                        <div class="swiper-slide"><img src="{% static 'society/image/u211.jpg' %}" alt=""></div>
                    </div>
                <!-- 如果需要分页器 -->
                    <div class="swiper-pagination"></div>

                    <!-- 如果需要导航按钮 -->
                    <div class="swiper-button-prev"></div>
                    <div class="swiper-button-next"></div>
		        </div>
                <img src="{% static 'society/image/u121.png' %}" alt="" class="ba_left_img1">
                <img src="{% static 'society/image/u999.png' %}" alt="" class="ba_left_img2">
            </div>
            <div class="ba_left_navga">
                <div class="point-categ {% if category == '1' %}black{% endif %}" href="{% url 'society:main_type' 1%}" ca=1>
                    <div class="title1_left_point {% if category == '1' %}one-point{% endif %}"></div>
                    <span>服务</span>
                </div>
                <div class="point-categ {% if category == '2' %}black{% endif %}" href="{% url 'society:main_type' 2%}" ca=2>
                    <div class="title1_left_point {% if category == '2' %}one-point{% endif %}"></div>
                    <span>文艺</span>
                </div>
                <div class="point-categ {% if category == '3' %}black{% endif %}" href="{% url 'society:main_type' 3%}" ca=3>
                    <div class="title1_left_point {% if category == '3' %}one-point{% endif %}"></div>
                    <span>体能</span>
                </div>
                <div class="point-categ {% if category == '4' %}black{% endif %}" href="{% url 'society:main_type' 4%}" ca=4>
                    <div class="title1_left_point {% if category == '4' %}one-point{% endif %}"></div>
                    <span>宗教</span>
                </div>
                <div class="point-categ new-add1 {% if category == '5' %}black{% endif %}" href="{% url 'society:main_type' 5%}" ca=5>
                    <div class="title1_left_point {% if category == '5' %}one-point{% endif %}"></div>
                    <span>理论研究</span>
                </div>
                <div class="point-categ new-add2 {% if category == '6' %}black{% endif %}" href="{% url 'society:main_type' 6%}" ca=6>
                    <div class="title1_left_point {% if category == '6' %}one-point{% endif %}"></div>
                    <span>专业科技</span>
                </div>
            </div>
            <div class="ba_left_bot">
                {% for article in articles %}
                <a href="{% url 'society:article_deta' article.id %}">
                    <div class="my-iss-li main-list">
                        <img class="arti-left" src="{% url 'media' article.image %}" alt="">
                        <div class="arti-cont">
                            <h4>{{ article.title }}</h4>
                            <div class="ppp">{{ article.content|slice:":40"|safe }}</div>
                            <div class="arti-cont-div clearf kenga">
                                <span class="arti-auth">{{ article.pr_user.username }} |</span>&nbsp;<span class="arti-time"> {{ article.distribute_date|date:"Y-m-d"  }}</span>
                                <div class="arti-share"><img src="{% static 'society/image/k_03@2x.png' %}" alt="">{{ article.view_count }}</div>
                                <div class="arti-view"><img src="{% static 'society/image/k_02.png' %}" alt="">{{ article.share_count }}</div>
                            </div>
                        </div>
                    </div>
                </a>
                {% endfor %}
                <button class="loding lod-many1">加载更多</button>
            </div>
        </div>

        <div class="ba_right">
            <div class="ba_right_top">
                <h4>快讯</h4>
                {% for fldate in flash_list %}
                <div class="new-flash">
                    <div class="flash-title" href="">
                        <img src="{% static 'society/image/b_n.png' %}" alt="" class="flash-img">
                        <span><a href="{% url 'society:flash_detail' fldate.id %}" class="ablack">{{ fldate.title }}</a></span>
                    </div>
                    <div class="flash-txt">
                        {{ fldate.digest }}
                    </div>
                    <div class="arti-cont-div clearf  flash-div">
                        <span class="arti-time">{{ fldate.distribute_date|minus }}</span>
                        <div class="arti-view">
                            <img src="{% static 'society/image/k_03.png' %}" alt="">
                            <a href="" class="kiss" style="font-size:13px;color: #5D5F62">分享</a>
                        </div>
                        <div class="arti-share">
                            <img src="{% static 'society/image/k_03@2x.png' %}" alt="">{{ fldate.share_count }}
                        </div>
                    </div>
                </div>
                {% endfor %}
                <a href="{% url 'society:flash' %}"><button class="loding but-infor lod-many2">查看更多资讯</button></a>
            </div>
            <div class="ba_right_bot">
                <h4>热门新闻</h4>
                <div class="right_bot_hot">
                    <img src="{% static 'society/image/lbyt.png' %}" alt="">
                    <div class="regis">去香港，打打底裤</div>
                </div>
                {% for hotnew in hotnew_list %}
                    <a href="{% url 'society:article_deta' hotnew.id %}">
                        <div class="right_bot_json clearf">
                            <img src="{% url 'media' hotnew.image %}" alt="">
                            <div class="right_json_div">
                                <div class="ppp" id="ppp">{{ hotnew.content|safe }}</div>
                                <div class="arti-cont-div time-span">
                                    <span>{{ hotnew.distribute_date|date:'Y-m-d' }}</span>
                                </div>
                            </div>
                        </div>
                    </a>
                {% endfor %}
            </div>

        </div>
    </body>
</html>
<script src="{% static 'society/js/jq3.js' %}"></script>
<script src="{% static 'js/swiper-4.3.5.min.js' %}"></script>
<script src="{% static 'society/js/basethree/main.js' %}"></script>
<script>
  	var mySwiper = new Swiper ('.swiper-container', {
  			// horizontal 水平方向
  			// vertical 设置为垂直方向
    		direction: 'horizontal',
    		loop: true,
            autoplay: true,

    	// 如果需要分页器
    	pagination: {
      		el: '.swiper-pagination',
   		},

	    // 如果需要前进后退按钮
	    navigation: {
	      nextEl: '.swiper-button-next',
	      prevEl: '.swiper-button-prev',
	    },

  	});
    cb = 0;
    $('.lod-many1').click(function () {
        $('.ba_left_bot').html('');
        type_a = $('.black').attr('ca');
        cb = cb + 1;
        $.ajax({
            url: "{% url 'society:main' %}/" + type_a + "?cb=" + cb,
            dataType: 'html',
            success: function(html) {
                $('.ba_left_bot').html(html);
            },
        })
    });

    $('#ppp>p').css({'margin-top': '0px'});
</script>