lxh/lxh/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from . import settings

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}, name='media'),
    path('admin/', admin.site.urls),
    path('pylxh/', include('society.urls')),
]

lxh/society/urls.py
#coding:utf-8
from django.urls import path, re_path
from . import views


app_name = 'society'
urlpatterns = [
    # 后台管理界面
    path('admin/login/', views.ad_login, name='ad_login'),
    path('admin/login_check/', views.ad_login_check, name='ad_login_check'),
    path('admin/index/', views.ad_index, name='ad_index'),
    # # 资讯管理
    # 栏目
    path('admin/category/', views.ad_category, name='ad_category'),
    path('admin/category/add/', views.ad_category_add, name='ad_category_add'),
    path('admin/category/add/2', views.ad_category_add2, name='ad_category_add2'),
    path('admin/category/change/', views.ad_category_change, name='ad_category_change'),
    path('admin/category/change2/', views.ad_category_change2, name='ad_category_change2'),
    path('admin/category/delete/', views.ad_category_delete, name='ad_category_delete'),
    path('admin/category/all_cate/', views.ad_all_cate, name='all_cate'),
    # 文章审核
    path('admin/art/', views.ad_article, name='ad_article'),
    path('admin/art/add', views.ad_article_add, name='article_add'),
    path('admin/art/change', views.ad_article_change, name='article_change'),
    path('admin/art/delete', views.ad_article_delete, name='article_delete'),
    path('admin/art/all_art/', views.ad_all_art, name='all_article'),
    # 审核是否通过
    path('admin/art/check/', views.art_check, name='art_check'),
    # # 系统管理
    # 公告
    path('admin/sys/notice', views.sys_notice, name='sys_notice'),
    # 友情链接
    path('admin/sys/blogrool', views.sys_blogrool, name='sys_blogrool'),
    path('admin/sys/blogrool/add', views.sys_blogrool_add, name='sys_blogrool_add'),
    # 数据备份
    path('admin/sys/data', views.sys_data, name='sys_data'),

    # 欢迎页
    path('admin/welcome/', views.welcome, name='welcome'),
    # 退出
    path('admin/logout/', views.ad_logout, name='ad_logout'),


    # 前端界面
    path('main/', views.main, name='main'),
    path('login/', views.login, name='login'),
    # 短信验证
    path('note/', views.note_code, name='note_code'),
    # 注册
    path('regis/', views.regis, name='regis'),
    path('regis_check/stu/', views.regis_check_stu, name='regis_check_stu'),
    path('regis_check/pri/', views.regis_check_pri, name='regis_check_pri'),
    # 忘记密码
    path('forget/pas/', views.forget_pas, name='forget_pas'),
    # 个人中心页面
    # 个人资料
    path('a/', views.geren, name='a'),
    path('change/data/', views.change_data, name='change_data'),
    path('iss/content/', views.iss_cont, name='iss_cont'),
    path('iss/<int:a>/', views.my_iss, name='my_iss'),
    path('i', views.my_vip, name='my_vip'),
    path('j', views.my_score, name='my_score'),
    path('k', views.pay, name='pay'),
    path('l', views.gift_ex, name='gift_ex'),
    path('g', views.new_message, name='new_message'),
    path('change/pwd/', views.change_pwd, name='change_pwd'),
    path('change/pwd2', views.change_pwd2, name='change_pwd2'),
    path('logout/', views.login_out, name='logout'),
    # 文章详情
    # path('article/deta/', views.article_deta, name='article_deta'),
    path('main/<int:a>', views.main_type, name='main_type'),
    path('fl', views.flash, name='flash'),
    path('fldeta<int:id>', views.flash_detail, name='flash_detail'),
    path('arti/<int:id>', views.article_deta, name='article_deta'),
    path('vote', views.di_vote, name='di_vote'),
    path('share/<int:id>', views.share_arti, name='share_arti'),
    path('share_suce', views.share_success, name='share_success'),
    path('com', views.comm, name='comm'),
]

lxh/tinymce/urls.py
# Copyright (c) 2008 Joost Cassee
# Licensed under the terms of the MIT License (see LICENSE.txt)
from django.conf.urls import url

from tinymce import views

urlpatterns = [
    url(r'^spellchecker/$', views.spell_check, name='tinymce-spellcheck'),
    url(r'^flatpages_link_list/$', views.flatpages_link_list, name='tinymce-linklist'),
    url(r'^compressor/$', views.compressor, name='tinymce-compressor'),
    url(r'^filebrowser/$', views.filebrowser, name='tinymce-filebrowser'),
]

lxh/society/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.


# 管理员
class AdminUser(User):
    info = models.CharField(max_length=200)


# 学生，游客
class Student(models.Model):
    username = models.CharField(max_length=20, unique=True)
    password = models.CharField(max_length=32)
    photo = models.ImageField(upload_to='%Y%m%d/',default='20181024/07.jpg')
    phone = models.CharField(max_length=11, unique=True)
    info = models.CharField(max_length=200, default='本人很懒，什么都没留下')
    score = models.PositiveSmallIntegerField(default=0)
    money = models.PositiveSmallIntegerField(default=0)
    choices = (
        (0, '普通用户'),
        (1, 'VIP 1'),
        (2, 'VIP 2'),
        (3, 'VIP 3'),
    )
    vip = models.PositiveSmallIntegerField(choices=choices, default=0)
    leave_count = models.PositiveSmallIntegerField(default=1)

    def validate_unique(self, exclude):
        super().validate_unique(exclude=['username', 'phone'])

    def __str__(self):
        return self.username


# 负责人 (不能评论)
class Principal(models.Model):
    username = models.CharField(max_length=20, unique=True)
    password = models.CharField(max_length=32)
    photo = models.ImageField(upload_to='%Y%m%d/',default='20181024/07.jpg')
    phone = models.CharField(max_length=11, unique=True)
    info = models.CharField(max_length=200, default='本人很懒，什么都没留下')
    score = models.PositiveSmallIntegerField(default=0)
    money = models.PositiveSmallIntegerField(default=0)
    choices = (
        (0, '普通用户'),
        (1, 'VIP 1'),
        (2, 'VIP 2'),
        (3, 'VIP 3'),
    )
    vip = models.PositiveSmallIntegerField(choices=choices, default=0)
    leave_count = models.PositiveSmallIntegerField(default=1)
    stu_num = models.CharField(max_length=10, default=151210223)
    user_code = models.CharField(max_length=10, default=0)
    mass = models.CharField(max_length=100)
    mass_code = models.CharField(max_length=200,unique=True)
    # vip_time = models.CharField(default=0,max_length=100)

    def validate_unique(self, exclude):
        super().validate_unique(exclude=['username', 'phone', 'mass_code'])

    # def is_expire(self):
    #     return

    def __str__(self):
        return self.username


# 栏目，分类
class Category(models.Model):
    type = models.CharField(max_length=20, unique=True)
    content = models.CharField(max_length=200, default='0')
    class Meta:
        ordering = ['id']

    def __str__(self):
        return self.type


# # 社团编码存放
class Corporate(models.Model):
    name = models.CharField(max_length=20)
    mass_code = models.CharField(max_length=200,default=0)

    def __str__(self):
        return self.name


# 社团文章表
class Article(models.Model):
    pr_user = models.ForeignKey(Principal, on_delete=models.CASCADE,related_name='articles')
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    title = models.CharField(max_length=50)
    source = models.CharField(max_length=50, null=True)
    digest = models.CharField(max_length=200)
    image = models.ImageField(upload_to='article/%Y%m%d/')
    content = models.TextField()
    view_count = models.PositiveSmallIntegerField(default=0)
    votes_count = models.PositiveSmallIntegerField(default=0)
    share_count = models.PositiveSmallIntegerField(default=0)
    distribute_date = models.DateTimeField(auto_now_add=True)
    status_choice = (
        (0, '待审核'),
        (1, '已发布'),
        (2, '未通过'),
    )
    status = models.PositiveSmallIntegerField(choices=status_choice, default=0)

    def __str__(self):
        return self.title


# 消息，回复表
class Message(models.Model):
    parent = models.ForeignKey('self', on_delete=models.CASCADE, related_name='child_messages', blank=True, null=True)
    pr_user = models.ForeignKey(Principal, on_delete=models.CASCADE, related_name='messages')
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='article_mess')
    content = models.CharField(max_length=100)
    send_time = models.DateTimeField(auto_now_add=True)


# 评论表
class Comment(models.Model):
    pr_user = models.ForeignKey(Principal, related_name='stu_coms', on_delete=models.CASCADE)
    article = models.ForeignKey(Article, related_name='comments', on_delete=models.CASCADE)
    content = models.CharField(max_length=100)
    send_time = models.DateTimeField(auto_now_add=True)


# 观察，点赞
class Sharevote(models.Model):
    pr_user = models.ForeignKey(Principal, on_delete=models.DO_NOTHING, related_name='stu_shares')
    article = models.ForeignKey(Article, on_delete=models.DO_NOTHING, related_name='arti_shares')
    yesno = models.PositiveSmallIntegerField(default=0)


# 积分账单表
class Bill(models.Model):
    author = models.ForeignKey(Principal, on_delete=models.CASCADE, related_name='bills')
    title = models.CharField(max_length=20, default='分享文章')
    score = models.CharField(max_length=10, default='+50')
    cost_date = models.DateTimeField(auto_now_add=True)


# 消费记录表
class Consume(models.Model):
    author = models.ForeignKey(Principal, on_delete=models.CASCADE, related_name='consumes')
    title = models.CharField(max_length=200)
    tran_money = models.PositiveSmallIntegerField(default=0)
    tran_date = models.DateTimeField(auto_now_add=True)


# 系统信息表
# class dx(models.Model):

lxh/society/forms.py
#coding:utf-8
from django import forms
from society.models import *
from django.utils.translation import ugettext_lazy as _


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['type', 'content']
        widgets = {
            'type': forms.TextInput(attrs={'class': 'input-text', 'id': 'type'}),
            'content': forms.Textarea(attrs={'class': 'textarea', 'onkeyup': '(this).Huitextarealength(this,200)', 'id': 'content'})
        }


# class StuForm(forms.Form):
#     class Meta:
#         model = Student
#         fields = ['username', 'password', 'phone']
#         widgets = {
#             'username': forms.TextInput(attrs={'class': 'form-control', 'id': 'contact_name', 'placeholder': '你的用户名...'}),
#             'password': forms.PasswordInput(attrs={'class': 'form-control', 'id': 'contact_pass', 'placeholder': '你的密码...'}),
#             'phone': forms.TextInput(attrs={'class': 'form-control', 'id': 'contact_phone', 'placeholder': '你的手机号...'})
#         }

# 社团负责人资料修改
class PriForm(forms.ModelForm):
    class Meta:
        model = Principal
        fields = ('photo', 'info', 'phone')
        labels = {'photo': _('头像'), 'info': _('简介'), 'phone': _('手机号')}
        widgets = {
            'info': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '写点什么？'}),
            'phone': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '输入手机号'})
        }


#密码修改
# class PripassForm(forms.Form):

lxh/society/templates/society/backstage/admin_index.html
<!DOCTYPE HTML>
<html>
<head>
<meta charset="utf-8">
<meta name="renderer" content="webkit|ie-comp|ie-stand">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no" />
<meta http-equiv="Cache-Control" content="no-siteapp" />
<link rel="Bookmark" href="/favicon.ico" >
<link rel="Shortcut Icon" href="/favicon.ico" />
<link rel="stylesheet" type="text/css" href="/static/h-ui/css/H-ui.min.css" />
<link rel="stylesheet" type="text/css" href="/static/h-ui.admin/css/H-ui.admin.css" />
<link rel="stylesheet" type="text/css" href="/static/lib/Hui-iconfont/1.0.8/iconfont.css" />
<link rel="stylesheet" type="text/css" href="/static/h-ui.admin/skin/default/skin.css" id="skin" />
<link rel="stylesheet" type="text/css" href="/static/h-ui.admin/css/style.css" />
    {% load static %}
<title>huihui</title>
</head>
<body>
<header class="navbar-wrapper">
	<div class="navbar navbar-fixed-top">
		<div class="container-fluid cl"> <a class="logo navbar-logo f-l mr-10 hidden-xs" href="">社团信息后台管理系统</a> <a class="logo navbar-logo-m f-l mr-10 visible-xs" href=""></a>
			<span class="logo navbar-slogan f-l mr-10 hidden-xs">v1.0</span>
			<a aria-hidden="false" class="nav-toggle Hui-iconfont visible-xs" href="javascript:;">&#xe667;</a>
		<nav id="Hui-userbar" class="nav navbar-nav navbar-userbar hidden-xs">
			<ul class="cl">
				<li>超级管理员</li>
				<li class="dropDown dropDown_hover">
					<a href="#" class="dropDown_A">admin <i class="Hui-iconfont">&#xe6d5;</i></a>
					<ul class="dropDown-menu menu radius box-shadow">
						<li><a href="javascript:;" onClick="myselfinfo()">个人信息</a></li>
						<li><a href="{% url 'society:ad_login' %}">切换账户</a></li>
						<li><a href="{% url 'society:ad_logout' %}?action=logout">退出</a></li>
				</ul>
			</li>
{#				<li id="Hui-msg"> <a href="#" title="消息"><span class="badge badge-danger">1</span><i class="Hui-iconfont" style="font-size:18px">&#xe68a;</i></a> </li>#}
				<li id="Hui-skin" class="dropDown right dropDown_hover"> <a href="javascript:;" class="dropDown_A" title="换肤"><i class="Hui-iconfont" style="font-size:18px">&#xe62a;</i></a>
					<ul class="dropDown-menu menu radius box-shadow">
						<li><a href="javascript:;" data-val="default" title="默认（黑色）">默认（黑色）</a></li>
						<li><a href="javascript:;" data-val="blue" title="蓝色">蓝色</a></li>
						<li><a href="javascript:;" data-val="green" title="绿色">绿色</a></li>
						<li><a href="javascript:;" data-val="red" title="红色">红色</a></li>
						<li><a href="javascript:;" data-val="yellow" title="黄色">黄色</a></li>
						<li><a href="javascript:;" data-val="orange" title="橙色">橙色</a></li>
					</ul>
				</li>
			</ul>
		</nav>
	</div>
</div>
</header>
<aside class="Hui-aside">
	<div class="menu_dropdown bk_2">
		<dl id="menu-article">
			<dt><i class="Hui-iconfont">&#xe616;</i> 资讯管理<i class="Hui-iconfont menu_dropdown-arrow">&#xe6d5;</i></dt>
			<dd>
				<ul>
					<li><a data-href="{% url 'society:ad_category' %}" data-title="类目管理" href="javascript:void(0)">类目管理</a></li>
                    <li><a data-href="{% url 'society:ad_article' %}" data-title="文章管理" href="javascript:void(0)">文章管理</a></li>
                    <li><a data-href="" data-title="社团审核" href="javascript:void(0)">社团审核</a></li>
                    <li><a data-href="" data-title="待定功能" href="javascript:void(0)">待定功能</a></li>
			    </ul>
		    </dd>
	    </dl>
		<dl id="menu-system">
			<dt><i class="Hui-iconfont">&#xe62e;</i> 系统管理<i class="Hui-iconfont menu_dropdown-arrow">&#xe6d5;</i></dt>
			<dd>
				<ul>
					<li><a data-href="{% url 'society:sys_notice' %}" data-title="系统公告" href="javascript:void(0)">系统公告</a></li>
					<li><a data-href="{% url 'society:sys_blogrool' %}" data-title="友情链接" href="javascript:void(0)">友情链接</a></li>
					<li><a data-href="{% url 'society:sys_data' %}" data-title="数据字典" href="javascript:void(0)">数据字典</a></li>
					<!--<li><a data-href="system-shielding.html" data-title="屏蔽词" href="javascript:void(0)">屏蔽词</a></li>-->
					<!--<li><a data-href="system-log.html" data-title="系统日志" href="javascript:void(0)">系统日志</a></li>-->
			</ul>
		</dd>
	</dl>
	</div>
</aside>
<div class="dislpayArrow hidden-xs"><a class="pngfix" href="javascript:void(0);" onClick="displaynavbar(this)"></a></div>
<section class="Hui-article-box">
	<div id="Hui-tabNav" class="Hui-tabNav hidden-xs">
		<div class="Hui-tabNav-wp">
			<ul id="min_title_list" class="acrossTab cl">
				<li class="active">
					<span title="我的桌面" data-href="{% url 'society:welcome' %}">我的桌面</span>
					<em></em></li>
		</ul>
	</div>
		<div class="Hui-tabNav-more btn-group"><a id="js-tabNav-prev" class="btn radius btn-default size-S" href="javascript:;"><i class="Hui-iconfont">&#xe6d4;</i></a><a id="js-tabNav-next" class="btn radius btn-default size-S" href="javascript:;"><i class="Hui-iconfont">&#xe6d7;</i></a></div>
</div>
	<div id="iframe_box" class="Hui-article">
		<div class="show_iframe">
			<div style="display:none" class="loading"></div>
			<iframe scrolling="yes" frameborder="0" src="{% url 'society:welcome' %}"></iframe>
	</div>
</div>
</section>

<div class="contextMenu" id="Huiadminmenu">
	<ul>
		<li id="closethis">关闭当前 </li>
		<li id="closeall">关闭全部 </li>
</ul>
</div>
<!--_footer 作为公共模版分离出去-->
<script type="text/javascript" src="/static/lib/jquery/1.9.1/jquery.min.js"></script>
<script type="text/javascript" src="/static/lib/layer/2.4/layer.js"></script>
<script type="text/javascript" src="/static/h-ui/js/H-ui.min.js"></script>
<script type="text/javascript" src="/static/h-ui.admin/js/H-ui.admin.js"></script> <!--/_footer 作为公共模版分离出去-->

<!--请在下方写此页面业务相关的脚本-->
<script type="text/javascript" src="/static/lib/jquery.contextmenu/jquery.contextmenu.r2.js"></script>

<script type="text/javascript">

    {% if messages %}
        {% for message in messages %}
            $.Huimodalalert("{{ message }}", 1000);
        {% endfor %}
    {% endif %}
/*个人信息*/
function myselfinfo(){
	layer.open({
		type: 1,
		area: ['300px','200px'],
		fix: false, //不固定
		maxmin: true,
		shade:0.4,
		title: '查看信息',
		content: '<div><br>&nbsp;&nbsp;&nbsp;&nbsp;一个即将毕业的苦逼程序员 <p><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;写于18.11.16，平院3504。</p></div>'
	});
}



</script>
</body>
</html>

lxh/society/templates/society/backstage/article-list.html
<!DOCTYPE HTML>
<html>
<head>
<meta charset="utf-8">
<meta name="renderer" content="webkit|ie-comp|ie-stand">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no" />
<meta http-equiv="Cache-Control" content="no-siteapp" />
<link rel="stylesheet" type="text/css" href="/static/h-ui/css/H-ui.min.css" />
<link rel="stylesheet" type="text/css" href="/static/h-ui.admin/css/H-ui.admin.css" />
<link rel="stylesheet" type="text/css" href="/static/lib/Hui-iconfont/1.0.8/iconfont.css" />
<link rel="stylesheet" type="text/css" href="/static/h-ui.admin/skin/default/skin.css" id="skin" />
<link rel="stylesheet" type="text/css" href="/static/h-ui.admin/css/style.css" />
<title>资讯列表</title>
</head>
<body>
<nav class="breadcrumb"><i class="Hui-iconfont">&#xe67f;</i> 首页 <span class="c-gray en">&gt;</span> 资讯管理 <span class="c-gray en">&gt;</span> 资讯列表 <a class="btn btn-success radius r" style="line-height:1.6em;margin-top:3px" href="javascript:location.replace(location.href);" title="刷新" ><i class="Hui-iconfont">&#xe68f;</i></a></nav>
<div class="page-container">
	<div class="text-c">
         <form action="{% url 'society:ad_article' %}" method="post">
            {% csrf_token %}
            <span class="select-box inline">
                <select name="c_id" class="select">
                    <option value="0">全部分类</option>
                    {% for category in art_list %}
                        <option value="{{ category.id }}" {% if c_id == category.id %} selected {% endif %}>{{ category }}</option>
                    {% endfor %}
                </select>
            </span> 日期范围：
            <input type="text" onfocus="WdatePicker({ maxDate:'#F{$dp.$D(\'logmax\')||\'%y-%M-%d\'}' })" id="logmin" class="input-text Wdate" style="width:120px;" name="start_date" value="{{ start_date}}">
            -
            <input type="text" onfocus="WdatePicker({ minDate:'#F{$dp.$D(\'logmin\')}',maxDate:'%y-%M-%d' })" id="logmax" class="input-text Wdate" style="width:120px;" name="end_date" value="{{ end_date}}">
            <input type="text" name="title" id="" placeholder=" 资讯名称" style="width:250px" class="input-text" value="{% if title %}{{ title }}{% endif %}">
            <input type="hidden" name="search" value="true">
            <button name="" id="" class="btn btn-success" type="submit"><i class="Hui-iconfont">&#xe665;</i> 搜资讯</button>
        </form>
    </div>
	<div class="cl pd-5 bg-1 bk-gray mt-20"> <span class="l"><a href="javascript:;" onclick="datadel()" class="btn btn-danger radius"><i class="Hui-iconfont">&#xe6e2;</i> 批量删除</a> <a class="btn btn-primary radius" data-title="添加资讯" href="{% url 'society:article_add' %}"><i class="Hui-iconfont">&#xe600;</i> 添加文章</a></span> <span class="r">共有数据：<strong>{{ articles.count }}</strong> 条</span> </div>
	<div class="mt-20">
		<table class="table table-border table-bordered table-bg table-hover table-sort table-responsive">
			<thead>
				<tr class="text-c">
					<th width="25"><input type="checkbox" name="" value=""></th>
					<th width="80">ID</th>
					<th>标题</th>
					<th width="80">分类</th>
					<th width="80">来源</th>
					<th width="120">更新时间</th>
					<th width="75">浏览次数</th>
					<th width="60">发布状态</th>
					<th width="120">操作</th>
				</tr>
			</thead>
			<tbody>
            {% for article in articles %}
				<tr class="text-c">
					<td><input type="checkbox" value="{{ article.id }}" name=""></td>
					<td class="art_id">{{ article.id }}</td>
					<td class="text-l"><u style="cursor:pointer" class="text-primary" onClick="article_edit('查看','article-zhang.html','10001')" title="查看">{{ article.title }}</u></td>
					<td>{{ article.category.type }}</td>
					<td>{{ article.source }}</td>
					<td>{{ article.distribute_date|date:'Y-m-d' }}</td>
					<td>{{ article.view_count }}</td>
					<td class="td-status"><span class="label {% if article.status == 2 %}label-danger {% elif article.status == 1 %} label-success {% else %} label-warning {% endif %} radius">{{ article.get_status_display }}</span></td>
					<td class="f-14 td-manage"><a style="text-decoration:none" onClick="article_shenhe(this,'{{ article.id }}')" href="javascript:;" title="审核">审核</a>  <a style="text-decoration:none" class="ml-5" onClick="article_del(this,'{{ article.id }}')" href="javascript:;" title="删除"><i class="Hui-iconfont">&#xe6e2;</i></a></td>
				</tr>
            {% endfor %}
			</tbody>
		</table>
        <!--<button id="fx">反选</button>-->
	</div>
</div>
<!--_footer 作为公共模版分离出去-->
<script type="text/javascript" src="/static/lib/jquery/1.9.1/jquery.min.js"></script>
<script type="text/javascript" src="/static/lib/layer/2.4/layer.js"></script>
<script type="text/javascript" src="/static/h-ui/js/H-ui.min.js"></script>
<script type="text/javascript" src="/static/h-ui.admin/js/H-ui.admin.js"></script> <!--/_footer 作为公共模版分离出去-->

<!--请在下方写此页面业务相关的脚本-->
<script type="text/javascript" src="/static/lib/My97DatePicker/4.8/WdatePicker.js"></script>
<script type="text/javascript" src="/static/lib/datatables/1.10.0/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="/static/lib/laypage/1.2/la"></script>
<script type="text/javascript">
    {% if messages %}
        {% for message in messages %}
            $.Huimodalalert("{{ message}}", 1000);
        {% endfor %}
    {% endif %}
$('.table-sort').dataTable({
	"aaSorting": [[ 1, "desc" ]],//默认第几个排序
	"bStateSave": true,//状态保存
	"pading":false,
	"aoColumnDefs": [
	  //{"bVisible": false, "aTargets": [ 3 ]} //控制列的隐藏显示
	  {"orderable":false,"aTargets":[0,7]}// 不参与排序的列
	]
});

/*资讯-添加*/
function article_add(title,url,w,h){
	var index = layer.open({
		type: 2,
		title: title,
		content: url
	});
	layer.full(index);
}
/*资讯-编辑*/
function article_edit(title,url,id,w,h){
	var index = layer.open({
		type: 2,
		title: title,
		content: url
	});
	layer.full(index);
}
/*资讯-删除*/
function article_del(obj,id){
	layer.confirm('确认要删除吗？',function(index){
		$.ajax({
			type: 'GET',
			url: '{% url 'society:article_delete' %}?id=' + id,
			dataType: 'json',
			success: function(data){
			    if (data.status == 1) {
			        $(obj).parents("tr").remove();
				    layer.msg(data.msg,{icon:1,time:1000});
                    location.reload();
                } else {
			        layer.msg(data.msg,{icon:6,time:1000});
                }
			},
			error:function(data) {
				console.log(data.msg);
			},
		});		
	});
}


/*资讯-审核*/
function article_shenhe(obj,id){
	layer.confirm('审核文章？', {
		btn: ['通过','不通过','取消'],
		shade: false,
		closeBtn: 0
	},
	function(){
		$.ajax({
			type: 'GET',
			url: "{% url 'society:art_check' %}?status=1&art_id=" + id,
			dataType: 'json',
			success: function(data){
				$(obj).parents("tr").find(".td-status").html('<span class="label label-success radius">已发布</span>');
				layer.msg('已发布', {icon:6,time:1000});
			},
		});
	},
	function(){
    	$.ajax({
    		type: 'GET',
    		url: "{% url 'society:art_check' %}?status=2&art_id=" + id,
    		dataType: 'json',
    		success: function(data){
				$(obj).parents("tr").find(".td-status").html('<span class="label label-danger radius">未通过</span>');
				layer.msg('未通过', {icon:5,time:1000});
    		},
    	});
	});
}


{# 反选 #}
$('#fx').click(function () {
    $('tbody input:checkbox').prop('checked', function(i, b) {
        return !b;
    });
});


{# 批量删除 #}
function datadel(obj, id) {
    layer.confirm('确认要删除吗？',function(index){
        var id_str = '';
        $('tbody input:checked').each(function (i, e) {
            id_str += $(e).val() + ',';
        });
        id_str = id_str.replace(/,$/, '');
        $.ajax({
            type: 'get',
            url: "{% url 'society:all_article' %}?id_str=" + id_str,
            success: function (data) {
                if (data.status == 1) {
                    $('tbody input:checked').parents('tr').remove();
                    layer.msg(data.msg,{icon:1,time:1000}, function () {
				        location.reload();
                    });
                } else {
			        layer.msg(data.msg,{icon:6,time:1000});
                }
            },
        })
    })
}



</script> 
</body>
</html>