lxh/lxh/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from . import settings

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}, name='media'),
    path('admin/', admin.site.urls),
    path('pylxh/', include('society.urls')),
]

lxh/society/urls.py
#coding:utf-8
from django.urls import path, re_path
from . import views


app_name = 'society'
urlpatterns = [
    # 后台管理界面
    path('admin/login/', views.ad_login, name='ad_login'),
    path('admin/login_check/', views.ad_login_check, name='ad_login_check'),
    path('admin/index/', views.ad_index, name='ad_index'),
    # # 资讯管理
    # 栏目
    path('admin/category/', views.ad_category, name='ad_category'),
    path('admin/category/add/', views.ad_category_add, name='ad_category_add'),
    path('admin/category/add/2', views.ad_category_add2, name='ad_category_add2'),
    path('admin/category/change/', views.ad_category_change, name='ad_category_change'),
    path('admin/category/change2/', views.ad_category_change2, name='ad_category_change2'),
    path('admin/category/delete/', views.ad_category_delete, name='ad_category_delete'),
    path('admin/category/all_cate/', views.ad_all_cate, name='all_cate'),
    # 文章审核
    path('admin/art/', views.ad_article, name='ad_article'),
    path('admin/art/add', views.ad_article_add, name='article_add'),
    path('admin/art/change', views.ad_article_change, name='article_change'),
    path('admin/art/delete', views.ad_article_delete, name='article_delete'),
    path('admin/art/all_art/', views.ad_all_art, name='all_article'),
    # 审核是否通过
    path('admin/art/check/', views.art_check, name='art_check'),
    # # 系统管理
    # 公告
    path('admin/sys/notice', views.sys_notice, name='sys_notice'),
    # 友情链接
    path('admin/sys/blogrool', views.sys_blogrool, name='sys_blogrool'),
    path('admin/sys/blogrool/add', views.sys_blogrool_add, name='sys_blogrool_add'),
    # 数据备份
    path('admin/sys/data', views.sys_data, name='sys_data'),

    # 欢迎页
    path('admin/welcome/', views.welcome, name='welcome'),
    # 退出
    path('admin/logout/', views.ad_logout, name='ad_logout'),


    # 前端界面
    path('main/', views.main, name='main'),
    path('login/', views.login, name='login'),
    # 短信验证
    path('note/', views.note_code, name='note_code'),
    # 注册
    path('regis/', views.regis, name='regis'),
    path('regis_check/stu/', views.regis_check_stu, name='regis_check_stu'),
    path('regis_check/pri/', views.regis_check_pri, name='regis_check_pri'),
    # 忘记密码
    path('forget/pas/', views.forget_pas, name='forget_pas'),
    # 个人中心页面
    # 个人资料
    path('a/', views.geren, name='a'),
    path('change/data/', views.change_data, name='change_data'),
    path('iss/content/', views.iss_cont, name='iss_cont'),
    path('iss/<int:a>/', views.my_iss, name='my_iss'),
    path('i', views.my_vip, name='my_vip'),
    path('j', views.my_score, name='my_score'),
    path('k', views.pay, name='pay'),
    path('l', views.gift_ex, name='gift_ex'),
    path('g', views.new_message, name='new_message'),
    path('change/pwd/', views.change_pwd, name='change_pwd'),
    path('change/pwd2', views.change_pwd2, name='change_pwd2'),
    path('logout/', views.login_out, name='logout'),
    # 文章详情
    # path('article/deta/', views.article_deta, name='article_deta'),
    path('main/<int:a>', views.main_type, name='main_type'),
    path('fl', views.flash, name='flash'),
    path('fldeta<int:id>', views.flash_detail, name='flash_detail'),
    path('arti/<int:id>', views.article_deta, name='article_deta'),
    path('vote', views.di_vote, name='di_vote'),
    path('share/<int:id>', views.share_arti, name='share_arti'),
    path('share_suce', views.share_success, name='share_success'),
    path('com', views.comm, name='comm'),
]

lxh/tinymce/urls.py
# Copyright (c) 2008 Joost Cassee
# Licensed under the terms of the MIT License (see LICENSE.txt)
from django.conf.urls import url

from tinymce import views

urlpatterns = [
    url(r'^spellchecker/$', views.spell_check, name='tinymce-spellcheck'),
    url(r'^flatpages_link_list/$', views.flatpages_link_list, name='tinymce-linklist'),
    url(r'^compressor/$', views.compressor, name='tinymce-compressor'),
    url(r'^filebrowser/$', views.filebrowser, name='tinymce-filebrowser'),
]

lxh/society/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.


# 管理员
class AdminUser(User):
    info = models.CharField(max_length=200)


# 学生，游客
class Student(models.Model):
    username = models.CharField(max_length=20, unique=True)
    password = models.CharField(max_length=32)
    photo = models.ImageField(upload_to='%Y%m%d/',default='20181024/07.jpg')
    phone = models.CharField(max_length=11, unique=True)
    info = models.CharField(max_length=200, default='本人很懒，什么都没留下')
    score = models.PositiveSmallIntegerField(default=0)
    money = models.PositiveSmallIntegerField(default=0)
    choices = (
        (0, '普通用户'),
        (1, 'VIP 1'),
        (2, 'VIP 2'),
        (3, 'VIP 3'),
    )
    vip = models.PositiveSmallIntegerField(choices=choices, default=0)
    leave_count = models.PositiveSmallIntegerField(default=1)

    def validate_unique(self, exclude):
        super().validate_unique(exclude=['username', 'phone'])

    def __str__(self):
        return self.username


# 负责人 (不能评论)
class Principal(models.Model):
    username = models.CharField(max_length=20, unique=True)
    password = models.CharField(max_length=32)
    photo = models.ImageField(upload_to='%Y%m%d/',default='20181024/07.jpg')
    phone = models.CharField(max_length=11, unique=True)
    info = models.CharField(max_length=200, default='本人很懒，什么都没留下')
    score = models.PositiveSmallIntegerField(default=0)
    money = models.PositiveSmallIntegerField(default=0)
    choices = (
        (0, '普通用户'),
        (1, 'VIP 1'),
        (2, 'VIP 2'),
        (3, 'VIP 3'),
    )
    vip = models.PositiveSmallIntegerField(choices=choices, default=0)
    leave_count = models.PositiveSmallIntegerField(default=1)
    stu_num = models.CharField(max_length=10, default=151210223)
    user_code = models.CharField(max_length=10, default=0)
    mass = models.CharField(max_length=100)
    mass_code = models.CharField(max_length=200,unique=True)
    # vip_time = models.CharField(default=0,max_length=100)

    def validate_unique(self, exclude):
        super().validate_unique(exclude=['username', 'phone', 'mass_code'])

    # def is_expire(self):
    #     return

    def __str__(self):
        return self.username


# 栏目，分类
class Category(models.Model):
    type = models.CharField(max_length=20, unique=True)
    content = models.CharField(max_length=200, default='0')
    class Meta:
        ordering = ['id']

    def __str__(self):
        return self.type


# # 社团编码存放
class Corporate(models.Model):
    name = models.CharField(max_length=20)
    mass_code = models.CharField(max_length=200,default=0)

    def __str__(self):
        return self.name


# 社团文章表
class Article(models.Model):
    pr_user = models.ForeignKey(Principal, on_delete=models.CASCADE,related_name='articles')
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    title = models.CharField(max_length=50)
    source = models.CharField(max_length=50, null=True)
    digest = models.CharField(max_length=200)
    image = models.ImageField(upload_to='article/%Y%m%d/')
    content = models.TextField()
    view_count = models.PositiveSmallIntegerField(default=0)
    votes_count = models.PositiveSmallIntegerField(default=0)
    share_count = models.PositiveSmallIntegerField(default=0)
    distribute_date = models.DateTimeField(auto_now_add=True)
    status_choice = (
        (0, '待审核'),
        (1, '已发布'),
        (2, '未通过'),
    )
    status = models.PositiveSmallIntegerField(choices=status_choice, default=0)

    def __str__(self):
        return self.title


# 消息，回复表
class Message(models.Model):
    parent = models.ForeignKey('self', on_delete=models.CASCADE, related_name='child_messages', blank=True, null=True)
    pr_user = models.ForeignKey(Principal, on_delete=models.CASCADE, related_name='messages')
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='article_mess')
    content = models.CharField(max_length=100)
    send_time = models.DateTimeField(auto_now_add=True)


# 评论表
class Comment(models.Model):
    pr_user = models.ForeignKey(Principal, related_name='stu_coms', on_delete=models.CASCADE)
    article = models.ForeignKey(Article, related_name='comments', on_delete=models.CASCADE)
    content = models.CharField(max_length=100)
    send_time = models.DateTimeField(auto_now_add=True)


# 观察，点赞
class Sharevote(models.Model):
    pr_user = models.ForeignKey(Principal, on_delete=models.DO_NOTHING, related_name='stu_shares')
    article = models.ForeignKey(Article, on_delete=models.DO_NOTHING, related_name='arti_shares')
    yesno = models.PositiveSmallIntegerField(default=0)


# 积分账单表
class Bill(models.Model):
    author = models.ForeignKey(Principal, on_delete=models.CASCADE, related_name='bills')
    title = models.CharField(max_length=20, default='分享文章')
    score = models.CharField(max_length=10, default='+50')
    cost_date = models.DateTimeField(auto_now_add=True)


# 消费记录表
class Consume(models.Model):
    author = models.ForeignKey(Principal, on_delete=models.CASCADE, related_name='consumes')
    title = models.CharField(max_length=200)
    tran_money = models.PositiveSmallIntegerField(default=0)
    tran_date = models.DateTimeField(auto_now_add=True)


# 系统信息表
# class dx(models.Model):

lxh/society/forms.py
#coding:utf-8
from django import forms
from society.models import *
from django.utils.translation import ugettext_lazy as _


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['type', 'content']
        widgets = {
            'type': forms.TextInput(attrs={'class': 'input-text', 'id': 'type'}),
            'content': forms.Textarea(attrs={'class': 'textarea', 'onkeyup': '(this).Huitextarealength(this,200)', 'id': 'content'})
        }


# class StuForm(forms.Form):
#     class Meta:
#         model = Student
#         fields = ['username', 'password', 'phone']
#         widgets = {
#             'username': forms.TextInput(attrs={'class': 'form-control', 'id': 'contact_name', 'placeholder': '你的用户名...'}),
#             'password': forms.PasswordInput(attrs={'class': 'form-control', 'id': 'contact_pass', 'placeholder': '你的密码...'}),
#             'phone': forms.TextInput(attrs={'class': 'form-control', 'id': 'contact_phone', 'placeholder': '你的手机号...'})
#         }

# 社团负责人资料修改
class PriForm(forms.ModelForm):
    class Meta:
        model = Principal
        fields = ('photo', 'info', 'phone')
        labels = {'photo': _('头像'), 'info': _('简介'), 'phone': _('手机号')}
        widgets = {
            'info': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '写点什么？'}),
            'phone': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '输入手机号'})
        }


#密码修改
# class PripassForm(forms.Form):

lxh/society/templates/society/baseone/forget_pas.html
{% extends 'society/index.html' %}

{% load static %}
{% block content %}
<header class="mb-5"><h1>Forget Pass</h1></header>
					<P class="mb-5">欢迎登陆本系统！<span class="forget-pass2"><a href="{% url 'society:regis' %}">没有账号？马上注册</a></span></P>
                    <form action="{% url 'society:forget_pas' %}" method="post" class="subscribe-form stu_login_error">
                        {% csrf_token %}
               	    	<div class="row form-section">
							<div class="col-md-10 col-sm-7 col-xs-7">
			                      <input type="text" class="form-control"  placeholder="你的手机号..." maxlength="11" required id="contact_phone" name="phone" /><span class="red err3">{{ err3 }}</span>
				  			</div>
                            <div class="col-md-8 col-sm-7 col-xs-7 re-code">
			                      <input name="code" type="text" class="form-control" id="contact_code" placeholder="验证码..."  /><span class="red err4">{{ err4 }}</span>
                                <div type="submit" class="btn tm-btn-subscribe btn-code btn1">获取验证码</div>
				  			</div>
                            <div class="col-md-10 col-sm-7 col-xs-7">
			                      <input name="password" type="password" class="form-control" id="contact_pass" placeholder="新密码..." onfocus="passfocu()" onblur="passblus()" required/><span class="red err2">{{ err2 }}</span>
				  			</div>
                            <div class="col-md-10 col-sm-7 col-xs-7">
			                      <input name="password2" type="password" class="form-control" id="contact_pass_new" placeholder="确认密码..." onfocus="passfocu()" onblur="pass2blus()" required/><span class="red err21"></span>
				  			</div>
                            <div class="col-md-8 col-sm-7 col-xs-7 ">
                                <input type="hidden" name="role" id="contact_role" value="学生">
                                <div class="role">
                                    <p class="role-stu">学生</p> <span class=""><img src="{% static 'society/image/下拉框箭头.png' %}" alt=""></span>
                                </div>
                                <div class="role-sele">
                                    <div class="role-sele-1">学生</div>
                                    <div class="role-sele-1">社团负责人</div>
                                </div>
				  			</div>
							<div class="col-md-10 col-sm-5 col-xs-5 qq">
								<button type="submit" class="tm-btn-subscribe" id="login">登录</button>
							</div>
						</div>
                    </form>
{% endblock %}
{% block js %}
    <script src="{% static 'society/js/regis.js' %}"></script>
    <script>
        {% if messages %}
        {% endif %}
    </script>
{% endblock %}

lxh/society/templates/society/baseone/gift_exchange.html
{% extends 'society/base.html' %}

{% block style %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'society/css/ba1_title.css' %}">
    <link rel="stylesheet" href="{% static 'society/css/base2.css' %}">
    <link rel="stylesheet" href="{% static 'society/css/baseone/pay.css' %}">
{% endblock %}

{% block head %}
    <button class="fbcontent clear" ><a href="{% url 'society:iss_cont' %}" class="iss">发布内容</a></button>
    <a href="{% url 'society:change_data' %}"><img src="{% url 'media' request.session.photo %}" alt="" width="35px" height="35px"></a>
{% endblock %}

{% block usname %}
    积分兑换会员
{% endblock %}

{% block content %}
    <form class="iss-success" action="{% url 'society:gift_ex' %}" method="post">
        {% csrf_token %}
        <div class="pay-top pay">
            <p>支付积分：<span class="blue pay-money">200</span> <span class="gray">原VIP{{ request.session.vip }}级抵扣0</span> </p>
        </div>
        <div class="level pay">
            <h4>选择购买方式</h4>
            <div class="level-bot">
                <div class="level-bot-div">
                  <input type="radio" name="score" checked value="2" class="pay-input">
                    <div>
                        <img src="{% static 'society/image/v1.png' %}" alt="">
                        <div class="wenzi">
                            <span class="blue f-sma">200积分</span>
                            <div class="gray">每个月可免费发布2条新闻</div>
                        </div>
                    </div>
                </div>
                <div class="level-bot-div">
                    <input type="radio" name="score" value="5" class="pay-input">
                   <div >
                    <img src="{% static 'society/image/v2.png' %}" alt="">
                    <div class="wenzi">
                        <span class="blue f-sma">500积分</span>
                        <div class="gray">每个月可免费发布5条新闻</div>
                    </div>
                    </div>
                </div>
                <div class="level-bot-div">
                    <input type="radio" name="score"  value="10" class="pay-input">
                    <div>
                        <img src="{% static 'society/image/v3.png' %}" alt="">
                        <div class="wenzi">
                            <span class="blue f-sma">1000积分</span>
                            <div class="gray">每个月可免费发布10条新闻</div>
                        </div>
                    </div>
                </div>
            </div>
            <span class="alert-pay">{{ error }}</span>
        </div>
        <button type="submit" class="btn btn-succ">确认支付</button>
    </form>

{% endblock %}

{% block js %}
    <script src="{% static 'society/js/iss.js' %}"></script>
{% endblock %}

lxh/society/templates/society/baseone/iss_content.html
{% extends 'society/base.html' %}

{% block style %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'society/css/ba1_title.css' %}">
    <link rel="stylesheet" href="{% static 'society/css/base2.css' %}">
    <link rel="stylesheet" href="{% static 'society/css/baseone/iss.css' %}">
    <script src="{% static 'tiny_mce/tiny_mce.js' %}"></script>
{% endblock %}

{% block head %}
    <button class="fbcontent clear" ><a href="{% url 'society:iss_cont' %}" class="iss">发布内容</a></button>
     <a href="{% url 'society:change_data' %}"><img src="{% url 'media' request.session.photo %}" alt="" width="35px" height="35px"></a>
{% endblock %}

{% block usname %}
    发布内容
{% endblock %}

{% block content %}
    <form action="{% url 'society:iss_cont' %}" class="form-horizontal iss_cont" method="post" enctype="multipart/form-data">
        {% csrf_token %}
      <div class="form-group form-group-lg">
        <label class="col-sm-2 control-label" for="formGroupInputLarge">内容名称:</label>
        <div class="col-sm-10">
          <input class="form-control show1" type="text" id="formGroupInputLarge" placeholder="文章名称" name="title" required maxlength="50">
            {{ error }}
            <span class="show_code1 codd"></span>
        </div>
      </div>
        <div class="form-group form-group-lg form-iss">
            <label class="col-sm-2 control-label" for="formGroupInputLarge">类型:</label>
            <div class="remove-d">
                <input class="btn btn-default btn-cat" type="radio" name='category' value='1' checked><span class="iss-but">服务</span>
            </div>
            <div class="remove-a">
                <input class="btn btn-default btn-cat" type="radio" name='category' value='2'><span class="iss-but">文艺</span>
            </div>
            <div class="remove-b">
                <input class="btn btn-default btn-cat" type="radio"  name='category' value='3'><span class="iss-but">体能</span>
            </div>
            <div class="remove-c">
                <input class="btn btn-default btn-cat" type="radio" name='category' value='4'><span class="iss-but">宗教</span>
            </div>
            <div class="remove-e">
                <input class="btn btn-default btn-cat" type="radio" name='category' value='5'><span class="iss-but">理论研究</span>
            </div>
            <div class="remove-f">
                <input class="btn btn-default btn-cat" type="radio" name='category' value='6'><span class="iss-but">专业科技</span>
            </div>
        </div>
        <div class="form-group form-group-lg ai">
            <label class="col-sm-2 control-label" for="formGroupInputLarge">作者:</label>
            <input class="form-control author-source" type="text" id="formGroupInputLarge" placeholder="作者名" name="author" value="{{ request.session.username }}" required>
        </div>
        <div class="form-group form-group-lg ai">
            <label class="col-sm-2 control-label" for="formGroupInputLarge" >来源:</label>
            <input class="form-control author-source show2" type="text" id="formGroupInputLarge" placeholder="来源" name="source" maxlength="50">
            <span class="show_code2 codd"></span>
        </div>
        <div class="form-group form-group-lg">
            <label class="col-sm-2 control-label" for="formGroupInputLarge">摘要:</label>
            <div class="col-sm-10">
            <input class="form-control show3" type="text" id="formGroupInputLarge" placeholder="摘要内容" name="digest" required maxlength="200">
                <span class="show_code3 codd"></span>
            </div>
        </div>
        <div class="form-group form-group-lg">
            <label class="col-sm-2 control-label" for="id_image">内容封面:</label>
            <div class="col-sm-10">
                <input class="form-control file-img" type="file" id="why" name="image" required onchange="changepic(this)">
                <img src="{% static 'society/image/addjpg.png' %}" alt="">
                <img src="" id="show" alt="" width="243px" height="142px">
                <span class="file-img-font">图片大小不得大于3MB</span>
            </div>
        </div>
        <div class="form-group form-group-lg">
            <label class="col-sm-2 control-label" for="formGroupInputLarge">稿件内容:</label>
            <div class="col-sm-10">
                <textarea placeholder="文章主体" name="content" ></textarea>
            </div>
        </div>
    <button type="submit" class="btn btn-primary">发布</button>
    </form>
{% endblock %}

{% block js %}
    <script src="{% static 'society/js/iss.js' %}"></script>
    <script src="{% static 'js/textlimit.js' %}"></script>
    <script src="{% static 'tiny_mce/tiny_mce.js' %}"></script>
    <script>
         $('.show1').focus(function () {
             $('.codd').html('');
             $(this).textlimit('.show_code1', 50);
         });

         $('.show2').focus(function () {
             $('.codd').html('');
             $(this).textlimit('.show_code2', 50)
         });

         $('.show3').focus(function () {
             $('.codd').html('');
             $(this).textlimit('.show_code3', 200)
         });

          {# 富文本 #}
         tinyMCE.init({
             'mode': 'textareas',
             'theme': 'advanced',
             'width': 925,
             'height': 400,
         });
         function changepic() {
            var reads= new FileReader();
            f=document.getElementById('why').files[0];
            reads.readAsDataURL(f);
            reads.onload=function (e) {
                document.getElementById('show').src=this.result;
            };
            var aa=document.getElementById("why").value.toLowerCase().split('.');//以“.”分隔上传文件字符串
            // var aa=document.form1.userfile.value.toLowerCase().split('.');//以“.”分隔上传文件字符串
            if(aa[aa.length-1]=='gif'||aa[aa.length-1]=='jpg'||aa[aa.length-1]=='bmp'

            ||aa[aa.length-1]=='png'||aa[aa.length-1]=='jpeg')//判断图片格式
                {
                    var imagSize =  document.getElementById("why").files[0].size;
            alert("图片大小："+imagSize+"B");
                if(imagSize>1024*1024*3)
                alert("图片大小在3M以内，为："+imagSize/(1024*1024)+"M");
                return true;
                } else {
                    alert('请选择格式为*.jpg、*.gif、*.bmp、*.png、*.jpeg 的图片');//jpg和jpeg格式是一样的只是系统Windows认jpg，Mac OS认jpeg，
                    return false;
                }
         }
    </script>
{% endblock %}

lxh/society/templates/society/baseone/iss_success.html
{% extends 'society/base.html' %}

{% block style %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'society/css/ba1_title.css' %}">
    <link rel="stylesheet" href="{% static 'society/css/base2.css' %}">
    <link rel="stylesheet" href="{% static 'society/css/baseone/iss.css' %}">
{% endblock %}

{% block head %}
    <button class="fbcontent clear" ><a href="{% url 'society:iss_cont' %}" class="iss">发布内容</a></button>
{#    <img src="{% url 'media' request.session.photo %}" alt="" width="35px" height="35px" class="base-head-img bushuang">#}
    <a href="{% url 'society:change_data' %}"><img src="{% url 'media' request.session.photo %}" alt="" width="35px" height="35px"></a>
{% endblock %}

{% block usname %}
    提交成功
{% endblock %}

{% block content %}
    <div class="iss-success">
        <img src="{% static 'society/image/tjcg.png' %}" alt="">
        <span class="iss-success-one">提交成功</span>
        <span class="iss-success-two">请您耐心等待审核</span>
    </div>
    <button  class="btn btn-succ"><a href="{% url 'society:change_data' %}">返回首页</a></button>
{% endblock %}

lxh/society/templates/society/baseone/login.html
{% extends 'society/index.html' %}

{% load static %}
{% block content %}
<header class="mb-5"><h1>Login</h1></header>
					<P class="mb-5">欢迎登陆本系统！<span class="forget-pass2"><a href="{% url 'society:regis' %}">没有账号？马上注册</a></span></P>
                    <form action="{% url 'society:login' %}" method="post" class="subscribe-form stu_login_error">
                        {% csrf_token %}
               	    	<div class="row form-section">

							<div class="col-md-10 col-sm-7 col-xs-7">
			                      <input type="text" class="form-control"  placeholder="你的学号或手机号..." required id="contact_name" name="username" value="{% if request.session.stu_num %}{{ request.session.stu_num }}{% endif %}"/><span class="red error">{{ err1 }}</span>
				  			</div>
                            <div class="col-md-10 col-sm-7 col-xs-7">
			                      <input name="password" type="password" class="form-control" id="contact_pass" placeholder="你的密码..." value="{% if request.session.password %}{{ request.session.password }}{% endif %}" required/><span class="red error">{{ err2 }}</span>
				  			</div>
                            <div class="col-md-8 col-sm-7 col-xs-7 check1">
                                <input type="hidden" name="role" id="contact_role" value="学生">
                                <div class="role">
                                    <p class="role-stu">学生</p> <span class=""><img src="{% static 'society/image/下拉框箭头.png' %}" alt=""></span>
                                </div>
                                <div class="role-sele">
                                    <div class="role-sele-1">学生</div>
                                    <div class="role-sele-1">社团负责人</div>
                                </div>
				  			</div>
                            <div class="col-md-8 col-sm-7 col-xs-7 check2">
                                <span class="check-pas"><input type="checkbox" value="1" class="check-pas check-pas1" name="check" id="check-pas" checked><label for="check-pas">记住密码</label></span>
                                <span class="forget-pass"><a
                                    href="{% url 'society:forget_pas' %}">忘记密码？</a></span>
                            </div>
							<div class="col-md-10 col-sm-5 col-xs-5 qq">
								<button type="submit" class="tm-btn-subscribe" id="login">登录</button>
							</div>
						</div>
                    </form>
{% endblock %}

lxh/society/templates/society/baseone/pay.html
{% extends 'society/base.html' %}

{% block style %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'society/css/ba1_title.css' %}">
    <link rel="stylesheet" href="{% static 'society/css/basetwo/base2.css' %}">
    <link rel="stylesheet" href="{% static 'society/css/baseone/pay.css' %}">
{% endblock %}

{% block head %}
    <button class="fbcontent clear" ><a href="{% url 'society:iss_cont' %}" class="iss">发布内容</a></button>
    <a href="{% url 'society:change_data' %}"><img src="{% url 'media' request.session.photo %}" alt="" width="35px" height="35px"></a>
{% endblock %}

{% block usname %}
    支付
{% endblock %}

{% block content %}
    <form class="iss-success" action="{% url 'society:pay' %}" method="post">
        {% csrf_token %}
        <div class="pay-top pay">
            <p>支付金额：<span class="blue pay-money">￥2000</span> <span class="gray">原VIP{{ request.session.vip }}级抵扣0</span> </p>
        </div>
        <div class="level pay">
            <h4>选择购买方式</h4>
            <div class="level-bot">
                <div class="level-bot-div">
                  <input type="radio" name="money" checked value="2" class="pay-input">
                    <div>
                        <img src="{% static 'society/image/v1.png' %}" alt="">
                        <div class="wenzi">
                            <span class="blue f-sma">￥2000</span>
                            <div class="gray">每个月可免费发布2条新闻</div>
                        </div>
                    </div>
                </div>
                <div class="level-bot-div">
                    <input type="radio" name="money" value="5" class="pay-input">
                   <div >
                    <img src="{% static 'society/image/v2.png' %}" alt="">
                    <div class="wenzi">
                        <span class="blue f-sma">￥5000</span>
                        <div class="gray">每个月可免费发布5条新闻</div>
                    </div>
                    </div>
                </div>
                <div class="level-bot-div">
                    <input type="radio" name="money"  value="10" class="pay-input">
                    <div>
                        <img src="{% static 'society/image/v3.png' %}" alt="">
                        <div class="wenzi">
                            <span class="blue f-sma">￥10000</span>
                            <div class="gray">每个月可免费发布10条新闻</div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        <div class="pay">
            <h4>选择支付方式</h4>
            <div class="level-bot">
                <div class="pay-img">
                    <input type="radio" name="payname" value="wx" checked class="pay-name">
                    <img src="{% static 'society/image/we.png' %}" alt="">
                </div>
                <div class="pay-img">
                    <input type="radio" name="payname" value="zfb" class="pay-name">
                    <img src="{% static 'society/image/zfb.png' %}" alt="">
                </div>
            </div>
        </div>
        <button type="submit" class="btn btn-succ">确认支付</button>
    </form>

{% endblock %}

{% block js %}
    <script src="{% static 'society/js/iss.js' %}"></script>
{% endblock %}