lxh/lxh/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from . import settings

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}, name='media'),
    path('admin/', admin.site.urls),
    path('pylxh/', include('society.urls')),
]

lxh/society/urls.py
#coding:utf-8
from django.urls import path, re_path
from . import views


app_name = 'society'
urlpatterns = [
    # 后台管理界面
    path('admin/login/', views.ad_login, name='ad_login'),
    path('admin/login_check/', views.ad_login_check, name='ad_login_check'),
    path('admin/index/', views.ad_index, name='ad_index'),
    # # 资讯管理
    # 栏目
    path('admin/category/', views.ad_category, name='ad_category'),
    path('admin/category/add/', views.ad_category_add, name='ad_category_add'),
    path('admin/category/add/2', views.ad_category_add2, name='ad_category_add2'),
    path('admin/category/change/', views.ad_category_change, name='ad_category_change'),
    path('admin/category/change2/', views.ad_category_change2, name='ad_category_change2'),
    path('admin/category/delete/', views.ad_category_delete, name='ad_category_delete'),
    path('admin/category/all_cate/', views.ad_all_cate, name='all_cate'),
    # 文章审核
    path('admin/art/', views.ad_article, name='ad_article'),
    path('admin/art/add', views.ad_article_add, name='article_add'),
    path('admin/art/change', views.ad_article_change, name='article_change'),
    path('admin/art/delete', views.ad_article_delete, name='article_delete'),
    path('admin/art/all_art/', views.ad_all_art, name='all_article'),
    # 审核是否通过
    path('admin/art/check/', views.art_check, name='art_check'),
    # # 系统管理
    # 公告
    path('admin/sys/notice', views.sys_notice, name='sys_notice'),
    # 友情链接
    path('admin/sys/blogrool', views.sys_blogrool, name='sys_blogrool'),
    path('admin/sys/blogrool/add', views.sys_blogrool_add, name='sys_blogrool_add'),
    # 数据备份
    path('admin/sys/data', views.sys_data, name='sys_data'),

    # 欢迎页
    path('admin/welcome/', views.welcome, name='welcome'),
    # 退出
    path('admin/logout/', views.ad_logout, name='ad_logout'),


    # 前端界面
    path('main/', views.main, name='main'),
    path('login/', views.login, name='login'),
    # 短信验证
    path('note/', views.note_code, name='note_code'),
    # 注册
    path('regis/', views.regis, name='regis'),
    path('regis_check/stu/', views.regis_check_stu, name='regis_check_stu'),
    path('regis_check/pri/', views.regis_check_pri, name='regis_check_pri'),
    # 忘记密码
    path('forget/pas/', views.forget_pas, name='forget_pas'),
    # 个人中心页面
    # 个人资料
    path('a/', views.geren, name='a'),
    path('change/data/', views.change_data, name='change_data'),
    path('iss/content/', views.iss_cont, name='iss_cont'),
    path('iss/<int:a>/', views.my_iss, name='my_iss'),
    path('i', views.my_vip, name='my_vip'),
    path('j', views.my_score, name='my_score'),
    path('k', views.pay, name='pay'),
    path('l', views.gift_ex, name='gift_ex'),
    path('g', views.new_message, name='new_message'),
    path('change/pwd/', views.change_pwd, name='change_pwd'),
    path('change/pwd2', views.change_pwd2, name='change_pwd2'),
    path('logout/', views.login_out, name='logout'),
    # 文章详情
    # path('article/deta/', views.article_deta, name='article_deta'),
    path('main/<int:a>', views.main_type, name='main_type'),
    path('fl', views.flash, name='flash'),
    path('fldeta<int:id>', views.flash_detail, name='flash_detail'),
    path('arti/<int:id>', views.article_deta, name='article_deta'),
    path('vote', views.di_vote, name='di_vote'),
    path('share/<int:id>', views.share_arti, name='share_arti'),
    path('share_suce', views.share_success, name='share_success'),
    path('com', views.comm, name='comm'),
]

lxh/tinymce/urls.py
# Copyright (c) 2008 Joost Cassee
# Licensed under the terms of the MIT License (see LICENSE.txt)
from django.conf.urls import url

from tinymce import views

urlpatterns = [
    url(r'^spellchecker/$', views.spell_check, name='tinymce-spellcheck'),
    url(r'^flatpages_link_list/$', views.flatpages_link_list, name='tinymce-linklist'),
    url(r'^compressor/$', views.compressor, name='tinymce-compressor'),
    url(r'^filebrowser/$', views.filebrowser, name='tinymce-filebrowser'),
]

lxh/society/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.


# 管理员
class AdminUser(User):
    info = models.CharField(max_length=200)


# 学生，游客
class Student(models.Model):
    username = models.CharField(max_length=20, unique=True)
    password = models.CharField(max_length=32)
    photo = models.ImageField(upload_to='%Y%m%d/',default='20181024/07.jpg')
    phone = models.CharField(max_length=11, unique=True)
    info = models.CharField(max_length=200, default='本人很懒，什么都没留下')
    score = models.PositiveSmallIntegerField(default=0)
    money = models.PositiveSmallIntegerField(default=0)
    choices = (
        (0, '普通用户'),
        (1, 'VIP 1'),
        (2, 'VIP 2'),
        (3, 'VIP 3'),
    )
    vip = models.PositiveSmallIntegerField(choices=choices, default=0)
    leave_count = models.PositiveSmallIntegerField(default=1)

    def validate_unique(self, exclude):
        super().validate_unique(exclude=['username', 'phone'])

    def __str__(self):
        return self.username


# 负责人 (不能评论)
class Principal(models.Model):
    username = models.CharField(max_length=20, unique=True)
    password = models.CharField(max_length=32)
    photo = models.ImageField(upload_to='%Y%m%d/',default='20181024/07.jpg')
    phone = models.CharField(max_length=11, unique=True)
    info = models.CharField(max_length=200, default='本人很懒，什么都没留下')
    score = models.PositiveSmallIntegerField(default=0)
    money = models.PositiveSmallIntegerField(default=0)
    choices = (
        (0, '普通用户'),
        (1, 'VIP 1'),
        (2, 'VIP 2'),
        (3, 'VIP 3'),
    )
    vip = models.PositiveSmallIntegerField(choices=choices, default=0)
    leave_count = models.PositiveSmallIntegerField(default=1)
    stu_num = models.CharField(max_length=10, default=151210223)
    user_code = models.CharField(max_length=10, default=0)
    mass = models.CharField(max_length=100)
    mass_code = models.CharField(max_length=200,unique=True)
    # vip_time = models.CharField(default=0,max_length=100)

    def validate_unique(self, exclude):
        super().validate_unique(exclude=['username', 'phone', 'mass_code'])

    # def is_expire(self):
    #     return

    def __str__(self):
        return self.username


# 栏目，分类
class Category(models.Model):
    type = models.CharField(max_length=20, unique=True)
    content = models.CharField(max_length=200, default='0')
    class Meta:
        ordering = ['id']

    def __str__(self):
        return self.type


# # 社团编码存放
class Corporate(models.Model):
    name = models.CharField(max_length=20)
    mass_code = models.CharField(max_length=200,default=0)

    def __str__(self):
        return self.name


# 社团文章表
class Article(models.Model):
    pr_user = models.ForeignKey(Principal, on_delete=models.CASCADE,related_name='articles')
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    title = models.CharField(max_length=50)
    source = models.CharField(max_length=50, null=True)
    digest = models.CharField(max_length=200)
    image = models.ImageField(upload_to='article/%Y%m%d/')
    content = models.TextField()
    view_count = models.PositiveSmallIntegerField(default=0)
    votes_count = models.PositiveSmallIntegerField(default=0)
    share_count = models.PositiveSmallIntegerField(default=0)
    distribute_date = models.DateTimeField(auto_now_add=True)
    status_choice = (
        (0, '待审核'),
        (1, '已发布'),
        (2, '未通过'),
    )
    status = models.PositiveSmallIntegerField(choices=status_choice, default=0)

    def __str__(self):
        return self.title


# 消息，回复表
class Message(models.Model):
    parent = models.ForeignKey('self', on_delete=models.CASCADE, related_name='child_messages', blank=True, null=True)
    pr_user = models.ForeignKey(Principal, on_delete=models.CASCADE, related_name='messages')
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='article_mess')
    content = models.CharField(max_length=100)
    send_time = models.DateTimeField(auto_now_add=True)


# 评论表
class Comment(models.Model):
    pr_user = models.ForeignKey(Principal, related_name='stu_coms', on_delete=models.CASCADE)
    article = models.ForeignKey(Article, related_name='comments', on_delete=models.CASCADE)
    content = models.CharField(max_length=100)
    send_time = models.DateTimeField(auto_now_add=True)


# 观察，点赞
class Sharevote(models.Model):
    pr_user = models.ForeignKey(Principal, on_delete=models.DO_NOTHING, related_name='stu_shares')
    article = models.ForeignKey(Article, on_delete=models.DO_NOTHING, related_name='arti_shares')
    yesno = models.PositiveSmallIntegerField(default=0)


# 积分账单表
class Bill(models.Model):
    author = models.ForeignKey(Principal, on_delete=models.CASCADE, related_name='bills')
    title = models.CharField(max_length=20, default='分享文章')
    score = models.CharField(max_length=10, default='+50')
    cost_date = models.DateTimeField(auto_now_add=True)


# 消费记录表
class Consume(models.Model):
    author = models.ForeignKey(Principal, on_delete=models.CASCADE, related_name='consumes')
    title = models.CharField(max_length=200)
    tran_money = models.PositiveSmallIntegerField(default=0)
    tran_date = models.DateTimeField(auto_now_add=True)


# 系统信息表
# class dx(models.Model):

lxh/society/forms.py
#coding:utf-8
from django import forms
from society.models import *
from django.utils.translation import ugettext_lazy as _


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['type', 'content']
        widgets = {
            'type': forms.TextInput(attrs={'class': 'input-text', 'id': 'type'}),
            'content': forms.Textarea(attrs={'class': 'textarea', 'onkeyup': '(this).Huitextarealength(this,200)', 'id': 'content'})
        }


# class StuForm(forms.Form):
#     class Meta:
#         model = Student
#         fields = ['username', 'password', 'phone']
#         widgets = {
#             'username': forms.TextInput(attrs={'class': 'form-control', 'id': 'contact_name', 'placeholder': '你的用户名...'}),
#             'password': forms.PasswordInput(attrs={'class': 'form-control', 'id': 'contact_pass', 'placeholder': '你的密码...'}),
#             'phone': forms.TextInput(attrs={'class': 'form-control', 'id': 'contact_phone', 'placeholder': '你的手机号...'})
#         }

# 社团负责人资料修改
class PriForm(forms.ModelForm):
    class Meta:
        model = Principal
        fields = ('photo', 'info', 'phone')
        labels = {'photo': _('头像'), 'info': _('简介'), 'phone': _('手机号')}
        widgets = {
            'info': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '写点什么？'}),
            'phone': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '输入手机号'})
        }


#密码修改
# class PripassForm(forms.Form):

lxh/society/templates/society/basetwo/change_data.html
{% extends 'society/base2.html' %}

{% block css %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'society/css/basetwo/change_data.css' %}">
{% endblock %}

{% block title %}
    个人资料
{% endblock %}

{% block content %}
    <form action="{% url 'society:change_data' %}" method="post" class="logform" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group left_label">
            {{ form.photo.label_tag }}
            <div class="head-zo">
                <img src="{% url 'media' request.session.photo %}" alt="" width="70px" height="70px" class="head-img show1">
                <div class="opcity">点击修改</div>
            </div>
            <input type="file" name="photo" id="id_photo" accept="image/*" required class="head-file">

        </div>
      <div class="form-group left_label">
          {{ form.info.label_tag }}
          {{ form.info }}
          <span class="err">{{ error1 }}</span>
      </div>
      <div class="form-group">
          {{ form.phone.label_tag }}
          {{ form.phone }}
          <span class="err">{{ error2 }}</span>
      </div>
      <button type="submit" class="btn btn-default">修改</button>
    </form>
{% endblock %}

{% block js %}
    <script></script>
    <script>
        $('#id_photo').change(function(e) {
            var _URL = window.URL || window.webkitURL;
            var file, img;
            if ((file = this.files[0])) {
                img = new Image();
                img.onload = function() {
                    $('.show1').attr('src', this.src);
                    console.log(this.width)
                };
                img.src = _URL.createObjectURL(file);
            }
        })
    </script>
{% endblock %}

lxh/society/templates/society/basetwo/change_pwd.html
{% extends 'society/base2.html' %}
{% block css %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'society/css/basetwo/keniu_login.css' %}">
     <link rel="stylesheet" href="{% static 'society/css/basetwo/change_pwd.css' %}">
{% endblock %}

{% block title %}
    修改密码
{% endblock %}

{% block content %}
    <form action="{% url 'society:change_pwd' %}" method="post" class="regform forgetform phoneform">
        {% csrf_token %}
        <div class="form-group phone-note">
{#            {{ form.phone_num }}#}
            <input type="text" maxlength="11" placeholder="请输入手机号" class="form-control" name="phone" value="{{ phone }}" required>
            <span class="err err-note">{{ error1 }}</span>
            <span class="err">{{ error2 }}</span>
        </div>
        <div class="form-group">
            <input type="password" placeholder="请输入原始密码" class="form-control" name="old_pwd" value="{{ old_pwd }}" required>
            <span class="err">{{ error3 }}</span>
        </div>
        <button type="submit" class="btn btn-default">下一步</button>
    </form>
{% endblock %}

{% block js %}
    <script src="{% static 'society/js/basetwo/change_pwd.js' %}"></script>
{% endblock %}

lxh/society/templates/society/basetwo/change_pwd2.html
{% extends 'society/base2.html' %}
{% block css %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'society/css/basetwo/keniu_login.css'%}">
    <link rel="stylesheet" href="{% static 'society/css/basetwo/change_pwd.css' %}">
{% endblock %}

{% block title %}
    修改密码
{% endblock %}

{% block content %}
    <form action="{% url 'society:change_pwd2' %}" method="post" class="regform forgetform phoneform">
        {% csrf_token %}
        <div class="hidd">
            <input type="text" class="form-control" name="phone" value="{{ phone }}" required>
            <span class="err">{{ error3 }}</span>
        </div>
      <div class="form-group">
          <input type="password" placeholder="请输入新密码" class="form-control" name="new_pwd1" value="{{ new_pwd1 }}" required>
          <span class="err">{{ error1 }}</span>
      </div>
      <div class="form-group">
          <input type="password" placeholder="请确认密码" class="form-control" name="new_pwd2" value="{{ new_pwd2 }}" required>
          <span class="err">{{ error2 }}</span>
      </div>

      <button type="submit" class="btn btn-default">完成</button>
    </form>
{% endblock %}

lxh/society/templates/society/basetwo/my_iss.html
{% extends 'society/base2.html' %}

{% block css %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'society/css/basetwo/css.css' %}">
    <link rel="stylesheet" href="{% static 'society/css/basetwo/my_vip.css' %}">

{% endblock %}

{% block title %}
    我的发布
{% endblock %}

{% block content %}
    <div class="head">
        <div class="find_nav_list">
            <ul>
                <li class="find_nav_cur"><a href="{% url 'society:my_iss' 3%}">全部</a></li>
                <li><a href="{% url 'society:my_iss' 0%}">审核中</a></li>
                <li><a href="{% url 'society:my_iss' 1%}">审核通过</a></li>
                <li><a href="{% url 'society:my_iss' 2%}">审核未通过</a></li>
                <li class="sideline"></li>
                <li class="sidelineone"></li>
            </ul>
        </div>
    </div>

    <div class="record">
        <div class="my-iss-ul">
            {% for each in contacts%}
                <a href="{% url 'society:article_deta' each.id %}">
                <div class="my-iss-li">
                    <img class="arti-left" src="{% url 'media' each.image %}" alt="">
                    <div class="arti-cont">
                        <h4>{{ each.title }}</h4>
                        <div class="ppp">{{ each.content|safe }}</div>
                        <div class="arti-cont-div clearf">
                            <span class="arti-auth">{{ each.pr_user.username }} |</span>&nbsp;<span class="arti-time"> {{ each.distribute_date|date:"Y-m-d"  }}</span>
                            <div class="arti-share"><img src="{% static 'society/image/k_02.png' %}" alt="">{{ each.share_count }}</div>
                            <div class="arti-view"><img src="{% static 'society/image/k_03@2x.png' %}" alt="">{{ each.view_count }}</div>
                        </div>
                    </div>
                    <div class="arti-right">
                        {% if each.status == 2 %}
                            <img src="{% static 'society/image/wtg.png' %}" alt="">
                        {% elif each.status == 1 %}
                            <img src="{% static 'society/image/dsh.png' %}" alt="">
                        {% elif each.status == 0 %}
                            <img src="{% static 'society/image/shz.png' %}" alt="">
                        {% endif %}
                    </div>
                </div>
            </a>
            {% endfor %}
        </div>

        <nav aria-label="Page navigation">
          <ul class="pagination pagination-lg">
              {% if contacts.has_previous %}
                <li>
                  <a href="?page={{ contacts.previous_page_number }}" aria-label="Previous" target="_parent">
                    <span aria-hidden="true">&laquo;</span>
                  </a>
                </li>
              {% endif %}

              {% for pg in contacts.paginator.page_range %}
                    {% if contacts.number == pg %}
                        <li class="active"><a href="?page={{ pg }}" target="_parent">{{ pg }}</a></li>
                    {% else %}
                        <li><a href="?page={{ pg }}" target="_parent">{{ pg }}</a></li>
                    {% endif %}
              {% endfor %}
              {% if contacts.has_next %}
                    <li>
                        <a href="?page={{ contacts.next_page_number }}" aria-label="Next" target="_parent">
                             <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
              {% endif %}
          </ul>
        </nav>
    </div>
{% endblock %}

{% block js %}
    <script src="{% static 'society/js/basetwo/my_vip.js' %}"></script>
    <script src="{% static 'society/js/basetwo/js.js' %}"></script>
{% endblock %}

lxh/society/templates/society/basetwo/my_iss_no.html
{% extends 'society/base2.html' %}

{% block css %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'society/css/basetwo/css.css' %}">
    <link rel="stylesheet" href="{% static 'society/css/basetwo/my_vip.css' %}">

{% endblock %}

{% block title %}
    我的发布
{% endblock %}

{% block content %}
    <div class="head">
        <div class="find_nav_list">
            <ul>
                <li class="find_nav_cur"><a href="javascript:void(0)">全部</a></li>
                <li><a href="javascript:void(0)">待审核</a></li>
                <li><a href="javascript:void(0)">审核中</a></li>
                <li><a href="javascript:void(0)">审核通过</a></li>
                <li><a href="javascript:void(0)">审核未通过</a></li>
                <li class="sideline"></li>
                <li class="sidelineone"></li>
            </ul>
        </div>
    </div>

    <div class="record-img">
        <img src="{% static 'society/image/zan.png' %}" alt="">
    </div>
{% endblock %}

{% block js %}
    <script src="{% static 'society/js/basetwo/my_vip.js' %}"></script>
    <script src="{% static 'society/js/basetwo/js.js' %}"></script>
{% endblock %}

lxh/society/templates/society/basetwo/my_score.html
{% extends 'society/base2.html' %}

{% block css %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'society/css/basetwo/my_vip.css' %}">
{% endblock %}

{% block title %}
    我的积分
{% endblock %}

{% block content %}
    <div class="head">
        <div class="vip-p">当前剩余积分：<span class="blue f-big">{{ request.session.score }}</span></div>
        <a href="{% url 'society:gift_ex' %}"><button class="vip-btn">兑换会员</button></a>
    </div>
    <hr>
    <div class="level dropdown">
        <div class="level-top">
            <div class="title1_left_point">
            </div>
            <span class="ba_title">积分说明</span>
            <span class="glyphicon glyphicon-triangle-right"></span>
        </div>
        <div class="level-bot level-bot-p">
            本积分与cny兑换比例为10:1cny。可与人棉币做等值兑换。<br>
            用户每分享一次新闻给好友，只有 好友允许获取微信openID并打开。即可获取1积分。最多5积分。同一个新闻每个用户第一次阅读有效...
        </div>
    </div>
    <hr>
    <div class="record">
        <div>
            <div class="title1_left_point">
            </div>
            <span class="ba_title">积分账单</span>
        </div>
        <ul class="record-ul">
            {% for each in contacts %}
            <li class="record-li">
                <span class="record-span1">{{ each.title }}</span>
                <span class="record-span2">{{ each.score }}</span>
                <span class="record-span3">{{ each.cost_date|date:"Y-m-d H:i" }}</span>
            </li>
            {% endfor %}
        </ul>
    </div>
    <nav aria-label="Page navigation">
          <ul class="pagination pagination-lg">
              {% if contacts.has_previous %}
                <li>
                  <a href="?page={{ contacts.previous_page_number }}" aria-label="Previous" target="_parent">
                    <span aria-hidden="true">&laquo;</span>
                  </a>
                </li>
              {% endif %}

              {% for pg in contacts.paginator.page_range %}
                    {% if contacts.number == pg %}
                        <li class="active"><a href="?page={{ pg }}" target="_parent">{{ pg }}</a></li>
                    {% else %}
                        <li><a href="?page={{ pg }}" target="_parent">{{ pg }}</a></li>
                    {% endif %}
              {% endfor %}
              {% if contacts.has_next %}
                    <li>
                        <a href="?page={{ contacts.next_page_number }}" aria-label="Next" target="_parent">
                             <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
              {% endif %}
          </ul>
    </nav>

{% endblock %}

{% block js %}
    <script src="{% static 'society/js/basetwo/my_vip.js' %}"></script>
{% endblock %}

lxh/society/templates/society/basetwo/my_vip.html
{% extends 'society/base2.html' %}

{% block css %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'society/css/basetwo/my_vip.css' %}">
{% endblock %}

{% block title %}
    我的会员
{% endblock %}

{% block content %}
    <div class="head">
        <div class="vip-p">当前 <span class="blue">VIP {{ request.session.vip }}</span>级，本月剩余发布次数：<span class="blue f-big">{{ request.session.leave_count }}</span>次</div>
        <a href="{% url 'society:pay' %}"><button class="vip-btn">续费 / 升级</button></a>
    </div>
    <hr>
    <div class="level">
        <div class="level-top">
            <div class="title1_left_point">
            </div>
            <span class="ba_title">会员等级说明</span>
        </div>
        <div class="level-bot">
            <div>
                <img src="{% static 'society/image/v1.png' %}" alt="">
                <div class="wenzi">
                    <span class="blue f-sma">￥2000</span>
                    <div class="gray">每个月可免费发布2条新闻</div>
                </div>
            </div>
            <div >
                <img src="{% static 'society/image/v2.png' %}" alt="">
                <div class="wenzi">
                    <span class="blue f-sma">￥5000</span>
                    <div class="gray">每个月可免费发布5条新闻</div>
                </div>
            </div>
            <div >
                <img src="{% static 'society/image/v3.png' %}" alt="">
                <div class="wenzi">
                    <span class="blue f-sma">￥10000</span>
                    <div class="gray">每个月可免费发布10条新闻</div>
                </div>
            </div>
        </div>
    </div>
    <hr>
    <div class="record">
        <div>
            <div class="title1_left_point">
            </div>
            <span class="ba_title">购买记录</span>
        </div>
        <ul class="record-ul">
            {% for each in contacts %}
            <li class="record-li">
                <span class="record-span1">{{ each.title }}</span>
                <span class="record-span2">￥{{ each.tran_money }}</span>
                <span class="record-span3">{{ each.tran_date|date:"Y-m-d H:i"}}</span>
            </li>
            {% endfor %}
        </ul>
    </div>
    <nav aria-label="Page navigation">
          <ul class="pagination pagination-lg">
              {% if contacts.has_previous %}
                <li>
                  <a href="?page={{ contacts.previous_page_number }}" aria-label="Previous" target="_parent">
                    <span aria-hidden="true">&laquo;</span>
                  </a>
                </li>
              {% endif %}

              {% for pg in contacts.paginator.page_range %}
                    {% if contacts.number == pg %}
                        <li class="active"><a href="?page={{ pg }}" target="_parent">{{ pg }}</a></li>
                    {% else %}
                        <li><a href="?page={{ pg }}" target="_parent">{{ pg }}</a></li>
                    {% endif %}
              {% endfor %}
              {% if contacts.has_next %}
                    <li>
                        <a href="?page={{ contacts.next_page_number }}" aria-label="Next" target="_parent">
                             <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
              {% endif %}
          </ul>
        </nav>

{% endblock %}

lxh/society/templates/society/basetwo/new_message.html
{% extends 'society/base2.html' %}

{% block css %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'society/css/basetwo/my_vip.css' %}">
{% endblock %}

{% block title %}
    消息通知
{% endblock %}

{% block content %}
    {% load poll_extras %}
    <div class="record">
        <ul class="record-ul message-tz">
            {% for each in contacts %}
            <li class="record-li">
                <span class="record-span1">{{ each.author.username }}评论了您的"{{ each.article.title }}"</span>
                <span class="record-span3">{{ each.send_time|minus }}</span>
            </li>
            {% endfor %}
        </ul>
    </div>
    <nav aria-label="Page navigation">
          <ul class="pagination pagination-lg">
              {% if contacts.has_previous %}
                <li>
                  <a href="?page={{ contacts.previous_page_number }}" aria-label="Previous" target="_parent">
                    <span aria-hidden="true">&laquo;</span>
                  </a>
                </li>
              {% endif %}

              {% for pg in contacts.paginator.page_range %}
                    {% if contacts.number == pg %}
                        <li class="active"><a href="?page={{ pg }}" target="_parent">{{ pg }}</a></li>
                    {% else %}
                        <li><a href="?page={{ pg }}" target="_parent">{{ pg }}</a></li>
                    {% endif %}
              {% endfor %}
              {% if contacts.has_next %}
                    <li>
                        <a href="?page={{ contacts.next_page_number }}" aria-label="Next" target="_parent">
                             <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
              {% endif %}

          </ul>
        </nav>

{% endblock %}

{% block js %}
    <script src="{% static 'society/js/basetwo/my_vip.js' %}"></script>
{% endblock %}